//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.CRM.COST_LKAHXZLTTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.COST_LKAHXZLTTService.COST_LKAHXZLTTSoap")]
    public interface COST_LKAHXZLTTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT[] ReadByParam(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int HXZLTTID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadTTGLinfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT ReadTTGLinfo(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByPublic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_HXZLTT[] ReadByPublic(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_HXZLTT model, int STAFFID, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_COST_LKAHXZLTT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hXZLTTIDField;
        
        private string hTYEARField;
        
        private string bEGINDATEField;
        
        private string eNDDATEField;
        
        private int lKAIDField;
        
        private int jXSIDField;
        
        private double bNDXSRWField;
        
        private double bNDALRWField;
        
        private double xSWCLField;
        
        private double aLWCLField;
        
        private double sPJEField;
        
        private double yHXJEField;
        
        private int lKAXSSJLXField;
        
        private double hTNDYGXSField;
        
        private double mQLKAXSSJField;
        
        private double lKABNDWCLField;
        
        private int fYHXXSField;
        
        private int lKAYJCMDSLField;
        
        private int cRMBAMDField;
        
        private string bEIZField;
        
        private int iSACTIVEField;
        
        private int sPZTField;
        
        private string oPINIONField;
        
        private int cJRField;
        
        private string cJSJField;
        
        private int xGRField;
        
        private string xGSJField;
        
        private string lKANAMEField;
        
        private string lKACRMIDField;
        
        private string jXSNAMEField;
        
        private string jXSSAPSNField;
        
        private string lKAXSSJLXDESField;
        
        private string fYHXXSDESField;
        
        private string cJRNAMEField;
        
        private string xGRNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HXZLTTID {
            get {
                return this.hXZLTTIDField;
            }
            set {
                this.hXZLTTIDField = value;
                this.RaisePropertyChanged("HXZLTTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HTYEAR {
            get {
                return this.hTYEARField;
            }
            set {
                this.hTYEARField = value;
                this.RaisePropertyChanged("HTYEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BEGINDATE {
            get {
                return this.bEGINDATEField;
            }
            set {
                this.bEGINDATEField = value;
                this.RaisePropertyChanged("BEGINDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int LKAID {
            get {
                return this.lKAIDField;
            }
            set {
                this.lKAIDField = value;
                this.RaisePropertyChanged("LKAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int JXSID {
            get {
                return this.jXSIDField;
            }
            set {
                this.jXSIDField = value;
                this.RaisePropertyChanged("JXSID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BNDXSRW {
            get {
                return this.bNDXSRWField;
            }
            set {
                this.bNDXSRWField = value;
                this.RaisePropertyChanged("BNDXSRW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double BNDALRW {
            get {
                return this.bNDALRWField;
            }
            set {
                this.bNDALRWField = value;
                this.RaisePropertyChanged("BNDALRW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double XSWCL {
            get {
                return this.xSWCLField;
            }
            set {
                this.xSWCLField = value;
                this.RaisePropertyChanged("XSWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double ALWCL {
            get {
                return this.aLWCLField;
            }
            set {
                this.aLWCLField = value;
                this.RaisePropertyChanged("ALWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double SPJE {
            get {
                return this.sPJEField;
            }
            set {
                this.sPJEField = value;
                this.RaisePropertyChanged("SPJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double YHXJE {
            get {
                return this.yHXJEField;
            }
            set {
                this.yHXJEField = value;
                this.RaisePropertyChanged("YHXJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int LKAXSSJLX {
            get {
                return this.lKAXSSJLXField;
            }
            set {
                this.lKAXSSJLXField = value;
                this.RaisePropertyChanged("LKAXSSJLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double HTNDYGXS {
            get {
                return this.hTNDYGXSField;
            }
            set {
                this.hTNDYGXSField = value;
                this.RaisePropertyChanged("HTNDYGXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double MQLKAXSSJ {
            get {
                return this.mQLKAXSSJField;
            }
            set {
                this.mQLKAXSSJField = value;
                this.RaisePropertyChanged("MQLKAXSSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double LKABNDWCL {
            get {
                return this.lKABNDWCLField;
            }
            set {
                this.lKABNDWCLField = value;
                this.RaisePropertyChanged("LKABNDWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int FYHXXS {
            get {
                return this.fYHXXSField;
            }
            set {
                this.fYHXXSField = value;
                this.RaisePropertyChanged("FYHXXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int LKAYJCMDSL {
            get {
                return this.lKAYJCMDSLField;
            }
            set {
                this.lKAYJCMDSLField = value;
                this.RaisePropertyChanged("LKAYJCMDSL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int CRMBAMD {
            get {
                return this.cRMBAMDField;
            }
            set {
                this.cRMBAMDField = value;
                this.RaisePropertyChanged("CRMBAMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string BEIZ {
            get {
                return this.bEIZField;
            }
            set {
                this.bEIZField = value;
                this.RaisePropertyChanged("BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int SPZT {
            get {
                return this.sPZTField;
            }
            set {
                this.sPZTField = value;
                this.RaisePropertyChanged("SPZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OPINION {
            get {
                return this.oPINIONField;
            }
            set {
                this.oPINIONField = value;
                this.RaisePropertyChanged("OPINION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CJSJ {
            get {
                return this.cJSJField;
            }
            set {
                this.cJSJField = value;
                this.RaisePropertyChanged("CJSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string XGSJ {
            get {
                return this.xGSJField;
            }
            set {
                this.xGSJField = value;
                this.RaisePropertyChanged("XGSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string LKANAME {
            get {
                return this.lKANAMEField;
            }
            set {
                this.lKANAMEField = value;
                this.RaisePropertyChanged("LKANAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string LKACRMID {
            get {
                return this.lKACRMIDField;
            }
            set {
                this.lKACRMIDField = value;
                this.RaisePropertyChanged("LKACRMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string JXSNAME {
            get {
                return this.jXSNAMEField;
            }
            set {
                this.jXSNAMEField = value;
                this.RaisePropertyChanged("JXSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string JXSSAPSN {
            get {
                return this.jXSSAPSNField;
            }
            set {
                this.jXSSAPSNField = value;
                this.RaisePropertyChanged("JXSSAPSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string LKAXSSJLXDES {
            get {
                return this.lKAXSSJLXDESField;
            }
            set {
                this.lKAXSSJLXDESField = value;
                this.RaisePropertyChanged("LKAXSSJLXDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string FYHXXSDES {
            get {
                return this.fYHXXSDESField;
            }
            set {
                this.fYHXXSDESField = value;
                this.RaisePropertyChanged("FYHXXSDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_COST_HXZLTT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hXZLTTIDField;
        
        private string hTYEARField;
        
        private string bEGINDATEField;
        
        private string eNDDATEField;
        
        private int lKAIDField;
        
        private int jXSIDField;
        
        private double bNDXSRWField;
        
        private double bNDALRWField;
        
        private double xSWCLField;
        
        private double aLWCLField;
        
        private double sPJEField;
        
        private double yHXJEField;
        
        private int lKAXSSJLXField;
        
        private double hTNDYGXSField;
        
        private double mQLKAXSSJField;
        
        private double lKABNDWCLField;
        
        private int fYHXXSField;
        
        private int lKAYJCMDSLField;
        
        private int cRMBAMDField;
        
        private string bEIZField;
        
        private int iSACTIVEField;
        
        private int sPZTField;
        
        private string oPINIONField;
        
        private int cJRField;
        
        private string cJSJField;
        
        private int xGRField;
        
        private string xGSJField;
        
        private string lKANAMEField;
        
        private string lKACRMIDField;
        
        private string jXSNAMEField;
        
        private string jXSSAPSNField;
        
        private string lKAXSSJLXDESField;
        
        private string fYHXXSDESField;
        
        private string cJRNAMEField;
        
        private string xGRNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HXZLTTID {
            get {
                return this.hXZLTTIDField;
            }
            set {
                this.hXZLTTIDField = value;
                this.RaisePropertyChanged("HXZLTTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HTYEAR {
            get {
                return this.hTYEARField;
            }
            set {
                this.hTYEARField = value;
                this.RaisePropertyChanged("HTYEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BEGINDATE {
            get {
                return this.bEGINDATEField;
            }
            set {
                this.bEGINDATEField = value;
                this.RaisePropertyChanged("BEGINDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int LKAID {
            get {
                return this.lKAIDField;
            }
            set {
                this.lKAIDField = value;
                this.RaisePropertyChanged("LKAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int JXSID {
            get {
                return this.jXSIDField;
            }
            set {
                this.jXSIDField = value;
                this.RaisePropertyChanged("JXSID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double BNDXSRW {
            get {
                return this.bNDXSRWField;
            }
            set {
                this.bNDXSRWField = value;
                this.RaisePropertyChanged("BNDXSRW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double BNDALRW {
            get {
                return this.bNDALRWField;
            }
            set {
                this.bNDALRWField = value;
                this.RaisePropertyChanged("BNDALRW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public double XSWCL {
            get {
                return this.xSWCLField;
            }
            set {
                this.xSWCLField = value;
                this.RaisePropertyChanged("XSWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public double ALWCL {
            get {
                return this.aLWCLField;
            }
            set {
                this.aLWCLField = value;
                this.RaisePropertyChanged("ALWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double SPJE {
            get {
                return this.sPJEField;
            }
            set {
                this.sPJEField = value;
                this.RaisePropertyChanged("SPJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double YHXJE {
            get {
                return this.yHXJEField;
            }
            set {
                this.yHXJEField = value;
                this.RaisePropertyChanged("YHXJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int LKAXSSJLX {
            get {
                return this.lKAXSSJLXField;
            }
            set {
                this.lKAXSSJLXField = value;
                this.RaisePropertyChanged("LKAXSSJLX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double HTNDYGXS {
            get {
                return this.hTNDYGXSField;
            }
            set {
                this.hTNDYGXSField = value;
                this.RaisePropertyChanged("HTNDYGXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double MQLKAXSSJ {
            get {
                return this.mQLKAXSSJField;
            }
            set {
                this.mQLKAXSSJField = value;
                this.RaisePropertyChanged("MQLKAXSSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double LKABNDWCL {
            get {
                return this.lKABNDWCLField;
            }
            set {
                this.lKABNDWCLField = value;
                this.RaisePropertyChanged("LKABNDWCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int FYHXXS {
            get {
                return this.fYHXXSField;
            }
            set {
                this.fYHXXSField = value;
                this.RaisePropertyChanged("FYHXXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int LKAYJCMDSL {
            get {
                return this.lKAYJCMDSLField;
            }
            set {
                this.lKAYJCMDSLField = value;
                this.RaisePropertyChanged("LKAYJCMDSL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int CRMBAMD {
            get {
                return this.cRMBAMDField;
            }
            set {
                this.cRMBAMDField = value;
                this.RaisePropertyChanged("CRMBAMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string BEIZ {
            get {
                return this.bEIZField;
            }
            set {
                this.bEIZField = value;
                this.RaisePropertyChanged("BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int SPZT {
            get {
                return this.sPZTField;
            }
            set {
                this.sPZTField = value;
                this.RaisePropertyChanged("SPZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OPINION {
            get {
                return this.oPINIONField;
            }
            set {
                this.oPINIONField = value;
                this.RaisePropertyChanged("OPINION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CJSJ {
            get {
                return this.cJSJField;
            }
            set {
                this.cJSJField = value;
                this.RaisePropertyChanged("CJSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string XGSJ {
            get {
                return this.xGSJField;
            }
            set {
                this.xGSJField = value;
                this.RaisePropertyChanged("XGSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string LKANAME {
            get {
                return this.lKANAMEField;
            }
            set {
                this.lKANAMEField = value;
                this.RaisePropertyChanged("LKANAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string LKACRMID {
            get {
                return this.lKACRMIDField;
            }
            set {
                this.lKACRMIDField = value;
                this.RaisePropertyChanged("LKACRMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string JXSNAME {
            get {
                return this.jXSNAMEField;
            }
            set {
                this.jXSNAMEField = value;
                this.RaisePropertyChanged("JXSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string JXSSAPSN {
            get {
                return this.jXSSAPSNField;
            }
            set {
                this.jXSSAPSNField = value;
                this.RaisePropertyChanged("JXSSAPSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string LKAXSSJLXDES {
            get {
                return this.lKAXSSJLXDESField;
            }
            set {
                this.lKAXSSJLXDESField = value;
                this.RaisePropertyChanged("LKAXSSJLXDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string FYHXXSDES {
            get {
                return this.fYHXXSDESField;
            }
            set {
                this.fYHXXSDESField = value;
                this.RaisePropertyChanged("FYHXXSDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface COST_LKAHXZLTTSoapChannel : Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.COST_LKAHXZLTTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COST_LKAHXZLTTSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.COST_LKAHXZLTTSoap>, Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.COST_LKAHXZLTTSoap {
        
        public COST_LKAHXZLTTSoapClient() {
        }
        
        public COST_LKAHXZLTTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COST_LKAHXZLTTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_LKAHXZLTTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_LKAHXZLTTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int Create(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public int Update(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken) {
            return base.Channel.Update(model, ptoken);
        }
        
        public Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT[] ReadByParam(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, int STAFFID, string ptoken) {
            return base.Channel.ReadByParam(model, STAFFID, ptoken);
        }
        
        public int Delete(int HXZLTTID, string ptoken) {
            return base.Channel.Delete(HXZLTTID, ptoken);
        }
        
        public Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT ReadTTGLinfo(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_LKAHXZLTT model, string ptoken) {
            return base.Channel.ReadTTGLinfo(model, ptoken);
        }
        
        public Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_HXZLTT[] ReadByPublic(Sonluk.UI.Model.CRM.COST_LKAHXZLTTService.CRM_COST_HXZLTT model, int STAFFID, string ptoken) {
            return base.Channel.ReadByPublic(model, STAFFID, ptoken);
        }
    }
}
