//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.LE.TRA.PriceService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Sonluk.com/API/LE/TRA/", ConfigurationName="LE.TRA.PriceService.PriceSoap")]
    public interface PriceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sonluk.com/API/LE/TRA/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.LE.TRA.PriceService.PriceInfo[] Read(int routeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sonluk.com/API/LE/TRA/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(Sonluk.UI.Model.LE.TRA.PriceService.PriceInfo[] nodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Sonluk.com/API/LE/TRA/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int routeID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Sonluk.com/API/LE/TRA/")]
    public partial class PriceInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int routeField;
        
        private string unitField;
        
        private int unitIDField;
        
        private decimal lowerWeightLimitField;
        
        private decimal upperWeightLimitField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
                this.RaisePropertyChanged("Route");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int UnitID {
            get {
                return this.unitIDField;
            }
            set {
                this.unitIDField = value;
                this.RaisePropertyChanged("UnitID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal LowerWeightLimit {
            get {
                return this.lowerWeightLimitField;
            }
            set {
                this.lowerWeightLimitField = value;
                this.RaisePropertyChanged("LowerWeightLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal UpperWeightLimit {
            get {
                return this.upperWeightLimitField;
            }
            set {
                this.upperWeightLimitField = value;
                this.RaisePropertyChanged("UpperWeightLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PriceSoapChannel : Sonluk.UI.Model.LE.TRA.PriceService.PriceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PriceSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.LE.TRA.PriceService.PriceSoap>, Sonluk.UI.Model.LE.TRA.PriceService.PriceSoap {
        
        public PriceSoapClient() {
        }
        
        public PriceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PriceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PriceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.LE.TRA.PriceService.PriceInfo[] Read(int routeID) {
            return base.Channel.Read(routeID);
        }
        
        public int Create(Sonluk.UI.Model.LE.TRA.PriceService.PriceInfo[] nodes) {
            return base.Channel.Create(nodes);
        }
        
        public int Delete(int routeID) {
            return base.Channel.Delete(routeID);
        }
    }
}
