//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.CRM.COST_LKAHXDJMXService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.COST_LKAHXDJMXService.COST_LKAHXDJMXSoap")]
    public interface COST_LKAHXDJMXSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX[] ReadByParam(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int HXDJMXID, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3163.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_COST_LKAHXDJMX : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hXDJMXIDField;
        
        private int hXDJTTIDField;
        
        private int cOSTITEMIDField;
        
        private string bEGINDATEField;
        
        private string eNDDATEField;
        
        private int fYHXXSField;
        
        private string cWHSBHField;
        
        private string cWHSBHDESField;
        
        private string cBZXBHDESField;
        
        private string cBZXBHField;
        
        private double hXJEField;
        
        private int slField;
        
        private string sLDESField;
        
        private double wSJEField;
        
        private string hXRQField;
        
        private int iSACTIVEField;
        
        private string bEIZField;
        
        private int cJRField;
        
        private string cJSJField;
        
        private int xGRField;
        
        private string xGSJField;
        
        private string cOSTITEMIDDESField;
        
        private string cJRNAMEField;
        
        private string xGRNAMEField;
        
        private string fYHXXSDESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int HXDJMXID {
            get {
                return this.hXDJMXIDField;
            }
            set {
                this.hXDJMXIDField = value;
                this.RaisePropertyChanged("HXDJMXID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int HXDJTTID {
            get {
                return this.hXDJTTIDField;
            }
            set {
                this.hXDJTTIDField = value;
                this.RaisePropertyChanged("HXDJTTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int COSTITEMID {
            get {
                return this.cOSTITEMIDField;
            }
            set {
                this.cOSTITEMIDField = value;
                this.RaisePropertyChanged("COSTITEMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BEGINDATE {
            get {
                return this.bEGINDATEField;
            }
            set {
                this.bEGINDATEField = value;
                this.RaisePropertyChanged("BEGINDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int FYHXXS {
            get {
                return this.fYHXXSField;
            }
            set {
                this.fYHXXSField = value;
                this.RaisePropertyChanged("FYHXXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CWHSBH {
            get {
                return this.cWHSBHField;
            }
            set {
                this.cWHSBHField = value;
                this.RaisePropertyChanged("CWHSBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CWHSBHDES {
            get {
                return this.cWHSBHDESField;
            }
            set {
                this.cWHSBHDESField = value;
                this.RaisePropertyChanged("CWHSBHDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CBZXBHDES {
            get {
                return this.cBZXBHDESField;
            }
            set {
                this.cBZXBHDESField = value;
                this.RaisePropertyChanged("CBZXBHDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CBZXBH {
            get {
                return this.cBZXBHField;
            }
            set {
                this.cBZXBHField = value;
                this.RaisePropertyChanged("CBZXBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double HXJE {
            get {
                return this.hXJEField;
            }
            set {
                this.hXJEField = value;
                this.RaisePropertyChanged("HXJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int SL {
            get {
                return this.slField;
            }
            set {
                this.slField = value;
                this.RaisePropertyChanged("SL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SLDES {
            get {
                return this.sLDESField;
            }
            set {
                this.sLDESField = value;
                this.RaisePropertyChanged("SLDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double WSJE {
            get {
                return this.wSJEField;
            }
            set {
                this.wSJEField = value;
                this.RaisePropertyChanged("WSJE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string HXRQ {
            get {
                return this.hXRQField;
            }
            set {
                this.hXRQField = value;
                this.RaisePropertyChanged("HXRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BEIZ {
            get {
                return this.bEIZField;
            }
            set {
                this.bEIZField = value;
                this.RaisePropertyChanged("BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string CJSJ {
            get {
                return this.cJSJField;
            }
            set {
                this.cJSJField = value;
                this.RaisePropertyChanged("CJSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string XGSJ {
            get {
                return this.xGSJField;
            }
            set {
                this.xGSJField = value;
                this.RaisePropertyChanged("XGSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string COSTITEMIDDES {
            get {
                return this.cOSTITEMIDDESField;
            }
            set {
                this.cOSTITEMIDDESField = value;
                this.RaisePropertyChanged("COSTITEMIDDES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string FYHXXSDES {
            get {
                return this.fYHXXSDESField;
            }
            set {
                this.fYHXXSDESField = value;
                this.RaisePropertyChanged("FYHXXSDES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface COST_LKAHXDJMXSoapChannel : Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.COST_LKAHXDJMXSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COST_LKAHXDJMXSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.COST_LKAHXDJMXSoap>, Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.COST_LKAHXDJMXSoap {
        
        public COST_LKAHXDJMXSoapClient() {
        }
        
        public COST_LKAHXDJMXSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COST_LKAHXDJMXSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_LKAHXDJMXSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_LKAHXDJMXSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int Create(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public int Update(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken) {
            return base.Channel.Update(model, ptoken);
        }
        
        public Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX[] ReadByParam(Sonluk.UI.Model.CRM.COST_LKAHXDJMXService.CRM_COST_LKAHXDJMX model, string ptoken) {
            return base.Channel.ReadByParam(model, ptoken);
        }
        
        public int Delete(int HXDJMXID, string ptoken) {
            return base.Channel.Delete(HXDJMXID, ptoken);
        }
    }
}
