CREATE OR REPLACE PROCEDURE PS_DropTable(name IN VARCHAR2)
AS   
  num NUMBER;   
BEGIN 
  SELECT COUNT(*) INTO num 
  FROM USER_TABLES 
  WHERE TABLE_NAME = UPPER(name); 
  IF   num>0   THEN   
    EXECUTE IMMEDIATE 'DROP TABLE ICRM.'||name;   
  END   IF;   
END;