//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.CRM.COST_KAYEARTTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.COST_KAYEARTTService.COST_KAYEARTTSoap")]
    public interface COST_KAYEARTTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSubmitCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateSubmitCount(int KAYEARTTID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByParam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT[] ReadByParam(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int KAYEARTTID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Verify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Verify(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRM_COST_KAYEARTT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int kAYEARTTIDField;
        
        private string hTYEARField;
        
        private int kHIDField;
        
        private string bEGINDATEField;
        
        private string eNDDATEField;
        
        private int mONTHCOUNTField;
        
        private string yEAR_LASTField;
        
        private string zQ_LASTField;
        
        private int mDSL_LASTField;
        
        private decimal pOS_LASTField;
        
        private decimal jH_LASTField;
        
        private decimal kP_LASTField;
        
        private string yEAR_THISField;
        
        private string zQ_THISField;
        
        private int mDSL_THISField;
        
        private decimal pOS_THISField;
        
        private decimal jH_THISField;
        
        private decimal kP_THISField;
        
        private string zQ_BEIZField;
        
        private string mDSL_BEIZField;
        
        private string pOS_BEIZField;
        
        private string jH_BEIZField;
        
        private string kP_BEIZField;
        
        private string bEIZField;
        
        private int iSACTIVEField;
        
        private int sUBMITCOUNTField;
        
        private int cJRField;
        
        private string cJSJField;
        
        private int xGRField;
        
        private string xGSJField;
        
        private string mcField;
        
        private string sAPSNField;
        
        private string cRMIDField;
        
        private string cJRNAMEField;
        
        private string xGRNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int KAYEARTTID {
            get {
                return this.kAYEARTTIDField;
            }
            set {
                this.kAYEARTTIDField = value;
                this.RaisePropertyChanged("KAYEARTTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HTYEAR {
            get {
                return this.hTYEARField;
            }
            set {
                this.hTYEARField = value;
                this.RaisePropertyChanged("HTYEAR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int KHID {
            get {
                return this.kHIDField;
            }
            set {
                this.kHIDField = value;
                this.RaisePropertyChanged("KHID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BEGINDATE {
            get {
                return this.bEGINDATEField;
            }
            set {
                this.bEGINDATEField = value;
                this.RaisePropertyChanged("BEGINDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ENDDATE {
            get {
                return this.eNDDATEField;
            }
            set {
                this.eNDDATEField = value;
                this.RaisePropertyChanged("ENDDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int MONTHCOUNT {
            get {
                return this.mONTHCOUNTField;
            }
            set {
                this.mONTHCOUNTField = value;
                this.RaisePropertyChanged("MONTHCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string YEAR_LAST {
            get {
                return this.yEAR_LASTField;
            }
            set {
                this.yEAR_LASTField = value;
                this.RaisePropertyChanged("YEAR_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ZQ_LAST {
            get {
                return this.zQ_LASTField;
            }
            set {
                this.zQ_LASTField = value;
                this.RaisePropertyChanged("ZQ_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int MDSL_LAST {
            get {
                return this.mDSL_LASTField;
            }
            set {
                this.mDSL_LASTField = value;
                this.RaisePropertyChanged("MDSL_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal POS_LAST {
            get {
                return this.pOS_LASTField;
            }
            set {
                this.pOS_LASTField = value;
                this.RaisePropertyChanged("POS_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal JH_LAST {
            get {
                return this.jH_LASTField;
            }
            set {
                this.jH_LASTField = value;
                this.RaisePropertyChanged("JH_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal KP_LAST {
            get {
                return this.kP_LASTField;
            }
            set {
                this.kP_LASTField = value;
                this.RaisePropertyChanged("KP_LAST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string YEAR_THIS {
            get {
                return this.yEAR_THISField;
            }
            set {
                this.yEAR_THISField = value;
                this.RaisePropertyChanged("YEAR_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ZQ_THIS {
            get {
                return this.zQ_THISField;
            }
            set {
                this.zQ_THISField = value;
                this.RaisePropertyChanged("ZQ_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int MDSL_THIS {
            get {
                return this.mDSL_THISField;
            }
            set {
                this.mDSL_THISField = value;
                this.RaisePropertyChanged("MDSL_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal POS_THIS {
            get {
                return this.pOS_THISField;
            }
            set {
                this.pOS_THISField = value;
                this.RaisePropertyChanged("POS_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal JH_THIS {
            get {
                return this.jH_THISField;
            }
            set {
                this.jH_THISField = value;
                this.RaisePropertyChanged("JH_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal KP_THIS {
            get {
                return this.kP_THISField;
            }
            set {
                this.kP_THISField = value;
                this.RaisePropertyChanged("KP_THIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ZQ_BEIZ {
            get {
                return this.zQ_BEIZField;
            }
            set {
                this.zQ_BEIZField = value;
                this.RaisePropertyChanged("ZQ_BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string MDSL_BEIZ {
            get {
                return this.mDSL_BEIZField;
            }
            set {
                this.mDSL_BEIZField = value;
                this.RaisePropertyChanged("MDSL_BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string POS_BEIZ {
            get {
                return this.pOS_BEIZField;
            }
            set {
                this.pOS_BEIZField = value;
                this.RaisePropertyChanged("POS_BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string JH_BEIZ {
            get {
                return this.jH_BEIZField;
            }
            set {
                this.jH_BEIZField = value;
                this.RaisePropertyChanged("JH_BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string KP_BEIZ {
            get {
                return this.kP_BEIZField;
            }
            set {
                this.kP_BEIZField = value;
                this.RaisePropertyChanged("KP_BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string BEIZ {
            get {
                return this.bEIZField;
            }
            set {
                this.bEIZField = value;
                this.RaisePropertyChanged("BEIZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int ISACTIVE {
            get {
                return this.iSACTIVEField;
            }
            set {
                this.iSACTIVEField = value;
                this.RaisePropertyChanged("ISACTIVE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int SUBMITCOUNT {
            get {
                return this.sUBMITCOUNTField;
            }
            set {
                this.sUBMITCOUNTField = value;
                this.RaisePropertyChanged("SUBMITCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CJSJ {
            get {
                return this.cJSJField;
            }
            set {
                this.cJSJField = value;
                this.RaisePropertyChanged("CJSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string XGSJ {
            get {
                return this.xGSJField;
            }
            set {
                this.xGSJField = value;
                this.RaisePropertyChanged("XGSJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string MC {
            get {
                return this.mcField;
            }
            set {
                this.mcField = value;
                this.RaisePropertyChanged("MC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string SAPSN {
            get {
                return this.sAPSNField;
            }
            set {
                this.sAPSNField = value;
                this.RaisePropertyChanged("SAPSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string CRMID {
            get {
                return this.cRMIDField;
            }
            set {
                this.cRMIDField = value;
                this.RaisePropertyChanged("CRMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface COST_KAYEARTTSoapChannel : Sonluk.UI.Model.CRM.COST_KAYEARTTService.COST_KAYEARTTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class COST_KAYEARTTSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.CRM.COST_KAYEARTTService.COST_KAYEARTTSoap>, Sonluk.UI.Model.CRM.COST_KAYEARTTService.COST_KAYEARTTSoap {
        
        public COST_KAYEARTTSoapClient() {
        }
        
        public COST_KAYEARTTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public COST_KAYEARTTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_KAYEARTTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public COST_KAYEARTTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public int Create(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public int Update(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken) {
            return base.Channel.Update(model, ptoken);
        }
        
        public int UpdateSubmitCount(int KAYEARTTID, string ptoken) {
            return base.Channel.UpdateSubmitCount(KAYEARTTID, ptoken);
        }
        
        public Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT[] ReadByParam(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, int STAFFID, string ptoken) {
            return base.Channel.ReadByParam(model, STAFFID, ptoken);
        }
        
        public int Delete(int KAYEARTTID, string ptoken) {
            return base.Channel.Delete(KAYEARTTID, ptoken);
        }
        
        public int Verify(Sonluk.UI.Model.CRM.COST_KAYEARTTService.CRM_COST_KAYEARTT model, string ptoken) {
            return base.Channel.Verify(model, ptoken);
        }
    }
}
