USE [HGMM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[LE_TRA_Receiver_Update]
    @SHRID int =0,
	@SHRJC varchar(50) =0,
	@SHRDW varchar(200)= ' ',
	@isDef bit=0
AS
BEGIN
	DECLARE @SAPNO varchar(20);
	
	SELECT @SAPNO=SAPNO
	FROM SP_SHR
	WHERE SHRID = @SHRID;
	
	IF @isDef=1
	BEGIN
		UPDATE SP_SHR
		SET  isDef=0
		WHERE SAPNO=@SAPNO;
	END
	
	UPDATE SP_SHR
	SET SHRJC = @SHRJC,SHRDW=@SHRDW,isDef =@isDef 
	WHERE SHRID = @SHRID;
	
	SELECT @SHRID ID;
END
GO