USE [HGMM]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[LE_TRA_City_Insert]
    @ZDFLID int = 0, 
    @ZDMC varchar(100) = ' ',
    @ZDSM varchar(500) = ' '
AS
BEGIN
	DECLARE @ID INT;
	DECLARE @DetailsID INT;

	IF @ZDFLID>0
	BEGIN
		SELECT @ID=MAX(ZDID)+1 
		FROM SP_TYZD;
		
		INSERT INTO SP_TYZD 
		VALUES (@ID, @ZDFLID, @ZDMC, @ZDSM, 0 );
		
	END	
	ELSE
	BEGIN
		SELECT @ID=MAX(ZDFLID)+1 
		FROM SP_ZDFL;
		
		INSERT INTO SP_ZDFL 
		VALUES (@ID, @ZDMC, 0, @ZDSM, 0 );
	END	
	
	SELECT @ID ID;
END
