USE [HGMM]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[LE_TRA_Receiver_Insert]
	@SHRJC varchar(50) = ' ',
	@SHRDW varchar(200)= ' ',
	@SAPNO varchar(20)= ' ',
	@isDef bit=0
AS
BEGIN
	DECLARE @ID INT;
				
	SELECT @ID=MAX(SHRID)+1 
	FROM SP_SHR;
	
	UPDATE HG_SYSINS
	SET SYSINT = @ID
	WHERE SYSNAME='SP_SHR';
	
	IF @isDef=1
	BEGIN
		UPDATE SP_SHR
		SET  isDef=0
		WHERE SAPNO=@SAPNO;
	END
		
	INSERT 
	INTO SP_SHR
	(SHRID,SHRJC,SHRDW,SAPNO,isDef)
	VALUES
	(@ID,@SHRJC,@SHRDW,@SAPNO,@isDef)
	
	SELECT @ID ID;
END
GO