SELECT * 
FROM SP_SHRDZ  a
LEFT JOIN SP_SHR  b
on a.SHRID  = b.SHRID 
WHERE zdid=175;


SELECT * FROM SP_SHRDZ a LEFT JOIN SP_SHR b on a.SHRID  = b.SHRID WHERE ZDID=175;


SELECT SXID,BJL,EJL,DJ FROM SP_TYJG WHERE SXID=:SXID AND BJL<=:BJL AND EJL>:EJL


SELECT SXID,BZDID,EZDID,SX,GSID FROM SP_SXB WHERE BZDID=1 AND EZDID=175;
SELECT SXID,BJL,EJL,DJ FROM SP_TYJG WHERE SXID=174 AND BJL<=0 AND EJL>0;


SELECT * FROM SP_SXB a LEFT JOIN SP_TYJG b on a.SXID = b.SXID where BJL<=0 AND EJL>0 AND BZDID=1 AND EZDID=175;


SELECT * FROM SP_SXB a LEFT JOIN SP_TYJG b ON a.SXID = b.SXID WHERE BJL<=@weight AND EJL>@weight AND BZDID=@source AND EZDID=@destination

SELECT LBID, LBMC FROM SP_HWLB WHERE isDelete=0;


SELECT *FROM SP_TYD WHERE tydid=20364;

SELECT MAX(TYDMXID)+1 
FROM SP_TYDMX
where TYDID=20365;


SELECT *
FROM SP_TYD 
WHERE tydid=203;

SELECT *
FROM SP_TYDMX
where TYDID=203;


exec LE_TRA_ConsignmentNote_Select 3;


SELECT A.HWID, A.HWMC, A.SAPBH, A.LBID, A.LBMC, A.DJSL, A.SLDWID, A.SLDWMC, A.DJMZ, A.DJJZ, A.ZLDWID, A.ZLDW, A.DJTJ, A.TJDWID, A.TJDW, B.XSID, B.XSMC FROM SP_HWQD A, SP_HWLB B WHERE A.LBID = B.LBID AND A.SAPBH = 
