SELECT A.ZDFLID,A.FLMC,B.ZDID,B.ZDMC
FROM SP_ZDFL A,SP_TYZD B
WHERE A.ZDFLID=B.ZDFLID 
	AND A.isDelete=0 
	AND B.isDelete=0
ORDER BY A.FLMC,B.ZDMC;

SELECT A.ZDFLID,A.FLMC,B.ZDID,B.ZDMC FROM SP_TYZD B left join  SP_ZDFL A on  A.ZDFLID=B.ZDFLID and A.isDelete=0 where B.isDelete=0 ORDER BY A.FLMC,B.ZDMC;