//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.HR.XZGL_XZDAService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HR.XZGL_XZDAService.WS_HR_XZGL_XZDASoap")]
    public interface WS_HR_XZGL_XZDASoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN INSERT(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN UPDATE(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_ALL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT_ALL(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_NOMY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT_NOMY(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AUTO_ADD_TO_FFJLMX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN AUTO_ADD_TO_FFJLMX(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_XZGL_XZDA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int xZDAIDField;
        
        private int rYIDField;
        
        private int gZLBIDField;
        
        private string gZLBNAMEField;
        
        private decimal tZQField;
        
        private decimal tZHField;
        
        private int tZYYField;
        
        private string sXDATEField;
        
        private int cJRField;
        
        private int xGRField;
        
        private string yGNAMEField;
        
        private string dEPTField;
        
        private string zZZTField;
        
        private string ghField;
        
        private string zZNOField;
        
        private string mYPWField;
        
        private int nSRSFField;
        
        private string nSRSBHField;
        
        private int zHLBField;
        
        private string fFJLIDField;
        
        private string gsField;
        
        private int sTAFFIDField;
        
        private string yGTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int XZDAID {
            get {
                return this.xZDAIDField;
            }
            set {
                this.xZDAIDField = value;
                this.RaisePropertyChanged("XZDAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RYID {
            get {
                return this.rYIDField;
            }
            set {
                this.rYIDField = value;
                this.RaisePropertyChanged("RYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GZLBID {
            get {
                return this.gZLBIDField;
            }
            set {
                this.gZLBIDField = value;
                this.RaisePropertyChanged("GZLBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GZLBNAME {
            get {
                return this.gZLBNAMEField;
            }
            set {
                this.gZLBNAMEField = value;
                this.RaisePropertyChanged("GZLBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TZQ {
            get {
                return this.tZQField;
            }
            set {
                this.tZQField = value;
                this.RaisePropertyChanged("TZQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal TZH {
            get {
                return this.tZHField;
            }
            set {
                this.tZHField = value;
                this.RaisePropertyChanged("TZH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TZYY {
            get {
                return this.tZYYField;
            }
            set {
                this.tZYYField = value;
                this.RaisePropertyChanged("TZYY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SXDATE {
            get {
                return this.sXDATEField;
            }
            set {
                this.sXDATEField = value;
                this.RaisePropertyChanged("SXDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string YGNAME {
            get {
                return this.yGNAMEField;
            }
            set {
                this.yGNAMEField = value;
                this.RaisePropertyChanged("YGNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string DEPT {
            get {
                return this.dEPTField;
            }
            set {
                this.dEPTField = value;
                this.RaisePropertyChanged("DEPT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ZZZT {
            get {
                return this.zZZTField;
            }
            set {
                this.zZZTField = value;
                this.RaisePropertyChanged("ZZZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string GH {
            get {
                return this.ghField;
            }
            set {
                this.ghField = value;
                this.RaisePropertyChanged("GH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ZZNO {
            get {
                return this.zZNOField;
            }
            set {
                this.zZNOField = value;
                this.RaisePropertyChanged("ZZNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MYPW {
            get {
                return this.mYPWField;
            }
            set {
                this.mYPWField = value;
                this.RaisePropertyChanged("MYPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int NSRSF {
            get {
                return this.nSRSFField;
            }
            set {
                this.nSRSFField = value;
                this.RaisePropertyChanged("NSRSF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NSRSBH {
            get {
                return this.nSRSBHField;
            }
            set {
                this.nSRSBHField = value;
                this.RaisePropertyChanged("NSRSBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int ZHLB {
            get {
                return this.zHLBField;
            }
            set {
                this.zHLBField = value;
                this.RaisePropertyChanged("ZHLB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string FFJLID {
            get {
                return this.fFJLIDField;
            }
            set {
                this.fFJLIDField = value;
                this.RaisePropertyChanged("FFJLID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string GS {
            get {
                return this.gsField;
            }
            set {
                this.gsField = value;
                this.RaisePropertyChanged("GS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string YGTYPE {
            get {
                return this.yGTYPEField;
            }
            set {
                this.yGTYPEField = value;
                this.RaisePropertyChanged("YGTYPE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_XZGL_XZDA_LIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int xZDAIDField;
        
        private int rYIDField;
        
        private int gZLBIDField;
        
        private string gZLBNAMEField;
        
        private decimal tZQField;
        
        private decimal tZHField;
        
        private int tZYYField;
        
        private string tZYYNAMEField;
        
        private string sXDATEField;
        
        private int cJRField;
        
        private string cJRNAMEField;
        
        private string cJTIMEField;
        
        private int xGRField;
        
        private string xGRNAMEField;
        
        private string xGTIMEField;
        
        private string ghField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int XZDAID {
            get {
                return this.xZDAIDField;
            }
            set {
                this.xZDAIDField = value;
                this.RaisePropertyChanged("XZDAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RYID {
            get {
                return this.rYIDField;
            }
            set {
                this.rYIDField = value;
                this.RaisePropertyChanged("RYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int GZLBID {
            get {
                return this.gZLBIDField;
            }
            set {
                this.gZLBIDField = value;
                this.RaisePropertyChanged("GZLBID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GZLBNAME {
            get {
                return this.gZLBNAMEField;
            }
            set {
                this.gZLBNAMEField = value;
                this.RaisePropertyChanged("GZLBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TZQ {
            get {
                return this.tZQField;
            }
            set {
                this.tZQField = value;
                this.RaisePropertyChanged("TZQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal TZH {
            get {
                return this.tZHField;
            }
            set {
                this.tZHField = value;
                this.RaisePropertyChanged("TZH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int TZYY {
            get {
                return this.tZYYField;
            }
            set {
                this.tZYYField = value;
                this.RaisePropertyChanged("TZYY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TZYYNAME {
            get {
                return this.tZYYNAMEField;
            }
            set {
                this.tZYYNAMEField = value;
                this.RaisePropertyChanged("TZYYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SXDATE {
            get {
                return this.sXDATEField;
            }
            set {
                this.sXDATEField = value;
                this.RaisePropertyChanged("SXDATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CJTIME {
            get {
                return this.cJTIMEField;
            }
            set {
                this.cJTIMEField = value;
                this.RaisePropertyChanged("CJTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string XGTIME {
            get {
                return this.xGTIMEField;
            }
            set {
                this.xGTIMEField = value;
                this.RaisePropertyChanged("XGTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string GH {
            get {
                return this.ghField;
            }
            set {
                this.ghField = value;
                this.RaisePropertyChanged("GH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_XZGL_XZDA_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Data.DataTable dataTableField;
        
        private MES_RETURN mES_RETURNField;
        
        private HR_XZGL_XZDA_LIST[] hR_XZGL_XZDA_LISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataTable DataTable {
            get {
                return this.dataTableField;
            }
            set {
                this.dataTableField = value;
                this.RaisePropertyChanged("DataTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public HR_XZGL_XZDA_LIST[] HR_XZGL_XZDA_LIST {
            get {
                return this.hR_XZGL_XZDA_LISTField;
            }
            set {
                this.hR_XZGL_XZDA_LISTField = value;
                this.RaisePropertyChanged("HR_XZGL_XZDA_LIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_HR_XZGL_XZDASoapChannel : Sonluk.UI.Model.HR.XZGL_XZDAService.WS_HR_XZGL_XZDASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_HR_XZGL_XZDASoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.HR.XZGL_XZDAService.WS_HR_XZGL_XZDASoap>, Sonluk.UI.Model.HR.XZGL_XZDAService.WS_HR_XZGL_XZDASoap {
        
        public WS_HR_XZGL_XZDASoapClient() {
        }
        
        public WS_HR_XZGL_XZDASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_HR_XZGL_XZDASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HR_XZGL_XZDASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HR_XZGL_XZDASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN INSERT(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken) {
            return base.Channel.INSERT(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN UPDATE(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken) {
            return base.Channel.UPDATE(model, LB, ptoken);
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken) {
            return base.Channel.SELECT(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT_ALL(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken) {
            return base.Channel.SELECT_ALL(model, LB, ptoken);
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA_SELECT SELECT_NOMY(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, int LB, string ptoken) {
            return base.Channel.SELECT_NOMY(model, LB, ptoken);
        }
        
        public Sonluk.UI.Model.HR.XZGL_XZDAService.MES_RETURN AUTO_ADD_TO_FFJLMX(Sonluk.UI.Model.HR.XZGL_XZDAService.HR_XZGL_XZDA model, string ptoken) {
            return base.Channel.AUTO_ADD_TO_FFJLMX(model, ptoken);
        }
    }
}
