//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.S5.SY_STAFF_DEPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="S5.SY_STAFF_DEPService.SY_STAFF_DEPSoap")]
    public interface SY_STAFF_DEPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEPList[] Read(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByDJ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEPList[] ReadByDJ(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN Create(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN UPDATE(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN DELETE(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN Update_All(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP[] model, int staffid, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_STAFF_DEP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTAFFIDField;
        
        private int dEPIDField;
        
        private int xJSTATUSField;
        
        private int cJSTATUSField;
        
        private int dJSTATUSField;
        
        private int tZSTATUSField;
        
        private int oPINTIDField;
        
        private int xFDJSTATUSField;
        
        private int sTDJSTATUSField;
        
        private int jFDJSTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DEPID {
            get {
                return this.dEPIDField;
            }
            set {
                this.dEPIDField = value;
                this.RaisePropertyChanged("DEPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int XJSTATUS {
            get {
                return this.xJSTATUSField;
            }
            set {
                this.xJSTATUSField = value;
                this.RaisePropertyChanged("XJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CJSTATUS {
            get {
                return this.cJSTATUSField;
            }
            set {
                this.cJSTATUSField = value;
                this.RaisePropertyChanged("CJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int DJSTATUS {
            get {
                return this.dJSTATUSField;
            }
            set {
                this.dJSTATUSField = value;
                this.RaisePropertyChanged("DJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TZSTATUS {
            get {
                return this.tZSTATUSField;
            }
            set {
                this.tZSTATUSField = value;
                this.RaisePropertyChanged("TZSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int OPINTID {
            get {
                return this.oPINTIDField;
            }
            set {
                this.oPINTIDField = value;
                this.RaisePropertyChanged("OPINTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int XFDJSTATUS {
            get {
                return this.xFDJSTATUSField;
            }
            set {
                this.xFDJSTATUSField = value;
                this.RaisePropertyChanged("XFDJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int STDJSTATUS {
            get {
                return this.sTDJSTATUSField;
            }
            set {
                this.sTDJSTATUSField = value;
                this.RaisePropertyChanged("STDJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int JFDJSTATUS {
            get {
                return this.jFDJSTATUSField;
            }
            set {
                this.jFDJSTATUSField = value;
                this.RaisePropertyChanged("JFDJSTATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        private string mSGNOField;
        
        private int iSCLMSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MSGNO {
            get {
                return this.mSGNOField;
            }
            set {
                this.mSGNOField = value;
                this.RaisePropertyChanged("MSGNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ISCLMSG {
            get {
                return this.iSCLMSGField;
            }
            set {
                this.iSCLMSGField = value;
                this.RaisePropertyChanged("ISCLMSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_STAFF_DEPList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTAFFIDField;
        
        private int dEPIDField;
        
        private int xJSTATUSField;
        
        private int cJSTATUSField;
        
        private string sNAMEField;
        
        private string dNAMEField;
        
        private int xIDField;
        
        private int cIDField;
        
        private string xNAMEField;
        
        private string cNAMEField;
        
        private int tZSTATUSField;
        
        private int dJSTATUSField;
        
        private string dJNAMEField;
        
        private int dIDField;
        
        private int xFDJSTATUSField;
        
        private int sTDJSTATUSField;
        
        private int jFDJSTATUSField;
        
        private int xFDJIDField;
        
        private int sTDJIDField;
        
        private int jFDJIDField;
        
        private string xFDJNAMEField;
        
        private string sTDJNAMEField;
        
        private string jFDJNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DEPID {
            get {
                return this.dEPIDField;
            }
            set {
                this.dEPIDField = value;
                this.RaisePropertyChanged("DEPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int XJSTATUS {
            get {
                return this.xJSTATUSField;
            }
            set {
                this.xJSTATUSField = value;
                this.RaisePropertyChanged("XJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CJSTATUS {
            get {
                return this.cJSTATUSField;
            }
            set {
                this.cJSTATUSField = value;
                this.RaisePropertyChanged("CJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SNAME {
            get {
                return this.sNAMEField;
            }
            set {
                this.sNAMEField = value;
                this.RaisePropertyChanged("SNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DNAME {
            get {
                return this.dNAMEField;
            }
            set {
                this.dNAMEField = value;
                this.RaisePropertyChanged("DNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XID {
            get {
                return this.xIDField;
            }
            set {
                this.xIDField = value;
                this.RaisePropertyChanged("XID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int CID {
            get {
                return this.cIDField;
            }
            set {
                this.cIDField = value;
                this.RaisePropertyChanged("CID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string XNAME {
            get {
                return this.xNAMEField;
            }
            set {
                this.xNAMEField = value;
                this.RaisePropertyChanged("XNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CNAME {
            get {
                return this.cNAMEField;
            }
            set {
                this.cNAMEField = value;
                this.RaisePropertyChanged("CNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TZSTATUS {
            get {
                return this.tZSTATUSField;
            }
            set {
                this.tZSTATUSField = value;
                this.RaisePropertyChanged("TZSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DJSTATUS {
            get {
                return this.dJSTATUSField;
            }
            set {
                this.dJSTATUSField = value;
                this.RaisePropertyChanged("DJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DJNAME {
            get {
                return this.dJNAMEField;
            }
            set {
                this.dJNAMEField = value;
                this.RaisePropertyChanged("DJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int DID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("DID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int XFDJSTATUS {
            get {
                return this.xFDJSTATUSField;
            }
            set {
                this.xFDJSTATUSField = value;
                this.RaisePropertyChanged("XFDJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int STDJSTATUS {
            get {
                return this.sTDJSTATUSField;
            }
            set {
                this.sTDJSTATUSField = value;
                this.RaisePropertyChanged("STDJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int JFDJSTATUS {
            get {
                return this.jFDJSTATUSField;
            }
            set {
                this.jFDJSTATUSField = value;
                this.RaisePropertyChanged("JFDJSTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int XFDJID {
            get {
                return this.xFDJIDField;
            }
            set {
                this.xFDJIDField = value;
                this.RaisePropertyChanged("XFDJID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int STDJID {
            get {
                return this.sTDJIDField;
            }
            set {
                this.sTDJIDField = value;
                this.RaisePropertyChanged("STDJID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int JFDJID {
            get {
                return this.jFDJIDField;
            }
            set {
                this.jFDJIDField = value;
                this.RaisePropertyChanged("JFDJID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string XFDJNAME {
            get {
                return this.xFDJNAMEField;
            }
            set {
                this.xFDJNAMEField = value;
                this.RaisePropertyChanged("XFDJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string STDJNAME {
            get {
                return this.sTDJNAMEField;
            }
            set {
                this.sTDJNAMEField = value;
                this.RaisePropertyChanged("STDJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string JFDJNAME {
            get {
                return this.jFDJNAMEField;
            }
            set {
                this.jFDJNAMEField = value;
                this.RaisePropertyChanged("JFDJNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SY_STAFF_DEPSoapChannel : Sonluk.UI.Model.S5.SY_STAFF_DEPService.SY_STAFF_DEPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SY_STAFF_DEPSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.S5.SY_STAFF_DEPService.SY_STAFF_DEPSoap>, Sonluk.UI.Model.S5.SY_STAFF_DEPService.SY_STAFF_DEPSoap {
        
        public SY_STAFF_DEPSoapClient() {
        }
        
        public SY_STAFF_DEPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SY_STAFF_DEPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_STAFF_DEPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_STAFF_DEPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEPList[] Read(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken) {
            return base.Channel.Read(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEPList[] ReadByDJ(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken) {
            return base.Channel.ReadByDJ(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN Create(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN UPDATE(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken) {
            return base.Channel.UPDATE(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN DELETE(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP model, string ptoken) {
            return base.Channel.DELETE(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_STAFF_DEPService.MES_RETURN Update_All(Sonluk.UI.Model.S5.SY_STAFF_DEPService.FIVES_SY_STAFF_DEP[] model, int staffid, string ptoken) {
            return base.Channel.Update_All(model, staffid, ptoken);
        }
    }
}
