//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.MES.SY_GZZX_SBHService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MES.SY_GZZX_SBHService.SY_GZZX_SBHSoap")]
    public interface SY_GZZX_SBHSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN INSERT(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN DELETE(string SBBH, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN UPDATE(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH[] SELECT(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_BY_STAFFID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH[] SELECT_BY_STAFFID(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_BY_TDNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD_SELECT SELECT_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_BY_TDNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN INSERT_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_BY_TDNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN DELETE_BY_TDNO(string TDNO, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_BY_TDNO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN UPDATE_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_LB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH_SELECT SELECT_LB(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_SY_GZZX_SBH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gcField;
        
        private string gZZXBHField;
        
        private string sBBHField;
        
        private string sBMSField;
        
        private string rEMARKField;
        
        private int iSACTIONField;
        
        private int pXMField;
        
        private string gZZXMSField;
        
        private int sBFLField;
        
        private int wLLBField;
        
        private string wLLBNAMEField;
        
        private int sTAFFIDField;
        
        private string cxField;
        
        private string fSBBHField;
        
        private string mACIPField;
        
        private int lbField;
        
        private string iMAGEField;
        
        private int jgField;
        
        private string rEMARK1Field;
        
        private string rEMARK2Field;
        
        private int tXTYPEField;
        
        private string tXTYPENAMEField;
        
        private string sBFLNAMEField;
        
        private string sBNOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GZZXBH {
            get {
                return this.gZZXBHField;
            }
            set {
                this.gZZXBHField = value;
                this.RaisePropertyChanged("GZZXBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SBBH {
            get {
                return this.sBBHField;
            }
            set {
                this.sBBHField = value;
                this.RaisePropertyChanged("SBBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SBMS {
            get {
                return this.sBMSField;
            }
            set {
                this.sBMSField = value;
                this.RaisePropertyChanged("SBMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ISACTION {
            get {
                return this.iSACTIONField;
            }
            set {
                this.iSACTIONField = value;
                this.RaisePropertyChanged("ISACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int PXM {
            get {
                return this.pXMField;
            }
            set {
                this.pXMField = value;
                this.RaisePropertyChanged("PXM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GZZXMS {
            get {
                return this.gZZXMSField;
            }
            set {
                this.gZZXMSField = value;
                this.RaisePropertyChanged("GZZXMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SBFL {
            get {
                return this.sBFLField;
            }
            set {
                this.sBFLField = value;
                this.RaisePropertyChanged("SBFL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int WLLB {
            get {
                return this.wLLBField;
            }
            set {
                this.wLLBField = value;
                this.RaisePropertyChanged("WLLB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string WLLBNAME {
            get {
                return this.wLLBNAMEField;
            }
            set {
                this.wLLBNAMEField = value;
                this.RaisePropertyChanged("WLLBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CX {
            get {
                return this.cxField;
            }
            set {
                this.cxField = value;
                this.RaisePropertyChanged("CX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FSBBH {
            get {
                return this.fSBBHField;
            }
            set {
                this.fSBBHField = value;
                this.RaisePropertyChanged("FSBBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string MACIP {
            get {
                return this.mACIPField;
            }
            set {
                this.mACIPField = value;
                this.RaisePropertyChanged("MACIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int LB {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
                this.RaisePropertyChanged("LB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string IMAGE {
            get {
                return this.iMAGEField;
            }
            set {
                this.iMAGEField = value;
                this.RaisePropertyChanged("IMAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int JG {
            get {
                return this.jgField;
            }
            set {
                this.jgField = value;
                this.RaisePropertyChanged("JG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string REMARK1 {
            get {
                return this.rEMARK1Field;
            }
            set {
                this.rEMARK1Field = value;
                this.RaisePropertyChanged("REMARK1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string REMARK2 {
            get {
                return this.rEMARK2Field;
            }
            set {
                this.rEMARK2Field = value;
                this.RaisePropertyChanged("REMARK2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int TXTYPE {
            get {
                return this.tXTYPEField;
            }
            set {
                this.tXTYPEField = value;
                this.RaisePropertyChanged("TXTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string TXTYPENAME {
            get {
                return this.tXTYPENAMEField;
            }
            set {
                this.tXTYPENAMEField = value;
                this.RaisePropertyChanged("TXTYPENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string SBFLNAME {
            get {
                return this.sBFLNAMEField;
            }
            set {
                this.sBFLNAMEField = value;
                this.RaisePropertyChanged("SBFLNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string SBNO {
            get {
                return this.sBNOField;
            }
            set {
                this.sBNOField = value;
                this.RaisePropertyChanged("SBNO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_SY_GZZX_SBH_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_RETURN mES_RETURNField;
        
        private MES_SY_GZZX_SBH[] mES_SY_GZZX_SBHField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public MES_SY_GZZX_SBH[] MES_SY_GZZX_SBH {
            get {
                return this.mES_SY_GZZX_SBHField;
            }
            set {
                this.mES_SY_GZZX_SBHField = value;
                this.RaisePropertyChanged("MES_SY_GZZX_SBH");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        private string mSGNOField;
        
        private int iSCLMSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MSGNO {
            get {
                return this.mSGNOField;
            }
            set {
                this.mSGNOField = value;
                this.RaisePropertyChanged("MSGNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ISCLMSG {
            get {
                return this.iSCLMSGField;
            }
            set {
                this.iSCLMSGField = value;
                this.RaisePropertyChanged("ISCLMSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_PD_TL_TD_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_PD_TL_TD[] mES_PD_TL_TDField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MES_PD_TL_TD[] MES_PD_TL_TD {
            get {
                return this.mES_PD_TL_TDField;
            }
            set {
                this.mES_PD_TL_TDField = value;
                this.RaisePropertyChanged("MES_PD_TL_TD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_PD_TL_TD : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tDNOField;
        
        private string sBBHField;
        
        private string tDREMARKField;
        
        private string gcField;
        
        private string gZZXBHField;
        
        private string sBMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TDNO {
            get {
                return this.tDNOField;
            }
            set {
                this.tDNOField = value;
                this.RaisePropertyChanged("TDNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SBBH {
            get {
                return this.sBBHField;
            }
            set {
                this.sBBHField = value;
                this.RaisePropertyChanged("SBBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TDREMARK {
            get {
                return this.tDREMARKField;
            }
            set {
                this.tDREMARKField = value;
                this.RaisePropertyChanged("TDREMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GZZXBH {
            get {
                return this.gZZXBHField;
            }
            set {
                this.gZZXBHField = value;
                this.RaisePropertyChanged("GZZXBH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SBMS {
            get {
                return this.sBMSField;
            }
            set {
                this.sBMSField = value;
                this.RaisePropertyChanged("SBMS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SY_GZZX_SBHSoapChannel : Sonluk.UI.Model.MES.SY_GZZX_SBHService.SY_GZZX_SBHSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SY_GZZX_SBHSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.MES.SY_GZZX_SBHService.SY_GZZX_SBHSoap>, Sonluk.UI.Model.MES.SY_GZZX_SBHService.SY_GZZX_SBHSoap {
        
        public SY_GZZX_SBHSoapClient() {
        }
        
        public SY_GZZX_SBHSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SY_GZZX_SBHSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_GZZX_SBHSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_GZZX_SBHSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN INSERT(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken) {
            return base.Channel.INSERT(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN DELETE(string SBBH, string ptoken) {
            return base.Channel.DELETE(SBBH, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN UPDATE(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken) {
            return base.Channel.UPDATE(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH[] SELECT(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken) {
            return base.Channel.SELECT(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH[] SELECT_BY_STAFFID(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken) {
            return base.Channel.SELECT_BY_STAFFID(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD_SELECT SELECT_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken) {
            return base.Channel.SELECT_BY_TDNO(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN INSERT_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken) {
            return base.Channel.INSERT_BY_TDNO(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN DELETE_BY_TDNO(string TDNO, string ptoken) {
            return base.Channel.DELETE_BY_TDNO(TDNO, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_RETURN UPDATE_BY_TDNO(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_PD_TL_TD model, string ptoken) {
            return base.Channel.UPDATE_BY_TDNO(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH_SELECT SELECT_LB(Sonluk.UI.Model.MES.SY_GZZX_SBHService.MES_SY_GZZX_SBH model, string ptoken) {
            return base.Channel.SELECT_LB(model, ptoken);
        }
    }
}
