//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.HR.DA_DAINFOService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HR.DA_DAINFOService.DA_DAINFOSoap")]
    public interface DA_DAINFOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_DADM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_DADM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM_SELECT SELECT_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_DADM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_DADM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN DELETE_DADM(int DADMID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_DAINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_DAINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO_SELECT SELECT_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_DAINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_DAINFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN DELETE_DAINFO(int DAID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT_DAJYJL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_DAJYJL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL_SELECT SELECT_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE_DAJYJL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DADM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dADMIDField;
        
        private string dADMField;
        
        private int dALBField;
        
        private string dALBNAMEField;
        
        private string dADMNAMEField;
        
        private int iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DADMID {
            get {
                return this.dADMIDField;
            }
            set {
                this.dADMIDField = value;
                this.RaisePropertyChanged("DADMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DADM {
            get {
                return this.dADMField;
            }
            set {
                this.dADMField = value;
                this.RaisePropertyChanged("DADM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DALB {
            get {
                return this.dALBField;
            }
            set {
                this.dALBField = value;
                this.RaisePropertyChanged("DALB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DALBNAME {
            get {
                return this.dALBNAMEField;
            }
            set {
                this.dALBNAMEField = value;
                this.RaisePropertyChanged("DALBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DADMNAME {
            get {
                return this.dADMNAMEField;
            }
            set {
                this.dADMNAMEField = value;
                this.RaisePropertyChanged("DADMNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAJYJL_LIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dAJYJLField;
        
        private int dAIDField;
        
        private int rYIDField;
        
        private string jYRQField;
        
        private string gHRQField;
        
        private string jYMDField;
        
        private string rEMARKField;
        
        private int jYZTField;
        
        private int iSDELETEField;
        
        private int cJRField;
        
        private int xGRField;
        
        private string sJGHRQField;
        
        private string ghField;
        
        private string yGNAMEField;
        
        private string gSNAMEField;
        
        private string dEPTNAMEField;
        
        private string xbField;
        
        private string zZZTNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DAJYJL {
            get {
                return this.dAJYJLField;
            }
            set {
                this.dAJYJLField = value;
                this.RaisePropertyChanged("DAJYJL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DAID {
            get {
                return this.dAIDField;
            }
            set {
                this.dAIDField = value;
                this.RaisePropertyChanged("DAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RYID {
            get {
                return this.rYIDField;
            }
            set {
                this.rYIDField = value;
                this.RaisePropertyChanged("RYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JYRQ {
            get {
                return this.jYRQField;
            }
            set {
                this.jYRQField = value;
                this.RaisePropertyChanged("JYRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GHRQ {
            get {
                return this.gHRQField;
            }
            set {
                this.gHRQField = value;
                this.RaisePropertyChanged("GHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string JYMD {
            get {
                return this.jYMDField;
            }
            set {
                this.jYMDField = value;
                this.RaisePropertyChanged("JYMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int JYZT {
            get {
                return this.jYZTField;
            }
            set {
                this.jYZTField = value;
                this.RaisePropertyChanged("JYZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SJGHRQ {
            get {
                return this.sJGHRQField;
            }
            set {
                this.sJGHRQField = value;
                this.RaisePropertyChanged("SJGHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string GH {
            get {
                return this.ghField;
            }
            set {
                this.ghField = value;
                this.RaisePropertyChanged("GH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string YGNAME {
            get {
                return this.yGNAMEField;
            }
            set {
                this.yGNAMEField = value;
                this.RaisePropertyChanged("YGNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GSNAME {
            get {
                return this.gSNAMEField;
            }
            set {
                this.gSNAMEField = value;
                this.RaisePropertyChanged("GSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string DEPTNAME {
            get {
                return this.dEPTNAMEField;
            }
            set {
                this.dEPTNAMEField = value;
                this.RaisePropertyChanged("DEPTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string XB {
            get {
                return this.xbField;
            }
            set {
                this.xbField = value;
                this.RaisePropertyChanged("XB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ZZZTNAME {
            get {
                return this.zZZTNAMEField;
            }
            set {
                this.zZZTNAMEField = value;
                this.RaisePropertyChanged("ZZZTNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAJYJL_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HR_DA_DAJYJL_LIST[] hR_DA_DAJYJL_LISTField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HR_DA_DAJYJL_LIST[] HR_DA_DAJYJL_LIST {
            get {
                return this.hR_DA_DAJYJL_LISTField;
            }
            set {
                this.hR_DA_DAJYJL_LISTField = value;
                this.RaisePropertyChanged("HR_DA_DAJYJL_LIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAJYJL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dAJYJLField;
        
        private int dAIDField;
        
        private int rYIDField;
        
        private string jYRQField;
        
        private string gHRQField;
        
        private string jYMDField;
        
        private string rEMARKField;
        
        private int jYZTField;
        
        private int iSDELETEField;
        
        private int cJRField;
        
        private int xGRField;
        
        private string sJGHRQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DAJYJL {
            get {
                return this.dAJYJLField;
            }
            set {
                this.dAJYJLField = value;
                this.RaisePropertyChanged("DAJYJL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DAID {
            get {
                return this.dAIDField;
            }
            set {
                this.dAIDField = value;
                this.RaisePropertyChanged("DAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RYID {
            get {
                return this.rYIDField;
            }
            set {
                this.rYIDField = value;
                this.RaisePropertyChanged("RYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JYRQ {
            get {
                return this.jYRQField;
            }
            set {
                this.jYRQField = value;
                this.RaisePropertyChanged("JYRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string GHRQ {
            get {
                return this.gHRQField;
            }
            set {
                this.gHRQField = value;
                this.RaisePropertyChanged("GHRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string JYMD {
            get {
                return this.jYMDField;
            }
            set {
                this.jYMDField = value;
                this.RaisePropertyChanged("JYMD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int JYZT {
            get {
                return this.jYZTField;
            }
            set {
                this.jYZTField = value;
                this.RaisePropertyChanged("JYZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string SJGHRQ {
            get {
                return this.sJGHRQField;
            }
            set {
                this.sJGHRQField = value;
                this.RaisePropertyChanged("SJGHRQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAINFO_LIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dAIDField;
        
        private int dADMIDField;
        
        private int dANOField;
        
        private string dAJSRQField;
        
        private int bGQXField;
        
        private string bGQXNAMEField;
        
        private string aJNAMEField;
        
        private int dAXSField;
        
        private string dAXSNAMEField;
        
        private int dAMJField;
        
        private string dAMJNAMEField;
        
        private int tZCOUNTField;
        
        private int wJCOUNTField;
        
        private int aLLCOUNTField;
        
        private string lYNAMEField;
        
        private string tM1Field;
        
        private string tM2Field;
        
        private string rEMARKField;
        
        private int dAZTField;
        
        private int iSDELETEField;
        
        private int cJRField;
        
        private string cJRNAMEField;
        
        private string cJTIMEField;
        
        private int xGRField;
        
        private string xGRNAMEField;
        
        private string xGRTIMEField;
        
        private string dADMField;
        
        private int dALBField;
        
        private string dALBNAMEField;
        
        private string dADMNAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DAID {
            get {
                return this.dAIDField;
            }
            set {
                this.dAIDField = value;
                this.RaisePropertyChanged("DAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DADMID {
            get {
                return this.dADMIDField;
            }
            set {
                this.dADMIDField = value;
                this.RaisePropertyChanged("DADMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DANO {
            get {
                return this.dANOField;
            }
            set {
                this.dANOField = value;
                this.RaisePropertyChanged("DANO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DAJSRQ {
            get {
                return this.dAJSRQField;
            }
            set {
                this.dAJSRQField = value;
                this.RaisePropertyChanged("DAJSRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int BGQX {
            get {
                return this.bGQXField;
            }
            set {
                this.bGQXField = value;
                this.RaisePropertyChanged("BGQX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BGQXNAME {
            get {
                return this.bGQXNAMEField;
            }
            set {
                this.bGQXNAMEField = value;
                this.RaisePropertyChanged("BGQXNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AJNAME {
            get {
                return this.aJNAMEField;
            }
            set {
                this.aJNAMEField = value;
                this.RaisePropertyChanged("AJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int DAXS {
            get {
                return this.dAXSField;
            }
            set {
                this.dAXSField = value;
                this.RaisePropertyChanged("DAXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DAXSNAME {
            get {
                return this.dAXSNAMEField;
            }
            set {
                this.dAXSNAMEField = value;
                this.RaisePropertyChanged("DAXSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DAMJ {
            get {
                return this.dAMJField;
            }
            set {
                this.dAMJField = value;
                this.RaisePropertyChanged("DAMJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DAMJNAME {
            get {
                return this.dAMJNAMEField;
            }
            set {
                this.dAMJNAMEField = value;
                this.RaisePropertyChanged("DAMJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int TZCOUNT {
            get {
                return this.tZCOUNTField;
            }
            set {
                this.tZCOUNTField = value;
                this.RaisePropertyChanged("TZCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int WJCOUNT {
            get {
                return this.wJCOUNTField;
            }
            set {
                this.wJCOUNTField = value;
                this.RaisePropertyChanged("WJCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ALLCOUNT {
            get {
                return this.aLLCOUNTField;
            }
            set {
                this.aLLCOUNTField = value;
                this.RaisePropertyChanged("ALLCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string LYNAME {
            get {
                return this.lYNAMEField;
            }
            set {
                this.lYNAMEField = value;
                this.RaisePropertyChanged("LYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TM1 {
            get {
                return this.tM1Field;
            }
            set {
                this.tM1Field = value;
                this.RaisePropertyChanged("TM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TM2 {
            get {
                return this.tM2Field;
            }
            set {
                this.tM2Field = value;
                this.RaisePropertyChanged("TM2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int DAZT {
            get {
                return this.dAZTField;
            }
            set {
                this.dAZTField = value;
                this.RaisePropertyChanged("DAZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string CJTIME {
            get {
                return this.cJTIMEField;
            }
            set {
                this.cJTIMEField = value;
                this.RaisePropertyChanged("CJTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string XGRTIME {
            get {
                return this.xGRTIMEField;
            }
            set {
                this.xGRTIMEField = value;
                this.RaisePropertyChanged("XGRTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string DADM {
            get {
                return this.dADMField;
            }
            set {
                this.dADMField = value;
                this.RaisePropertyChanged("DADM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int DALB {
            get {
                return this.dALBField;
            }
            set {
                this.dALBField = value;
                this.RaisePropertyChanged("DALB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DALBNAME {
            get {
                return this.dALBNAMEField;
            }
            set {
                this.dALBNAMEField = value;
                this.RaisePropertyChanged("DALBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DADMNAME {
            get {
                return this.dADMNAMEField;
            }
            set {
                this.dADMNAMEField = value;
                this.RaisePropertyChanged("DADMNAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAINFO_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HR_DA_DAINFO_LIST[] hR_DA_DAINFO_LISTField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HR_DA_DAINFO_LIST[] HR_DA_DAINFO_LIST {
            get {
                return this.hR_DA_DAINFO_LISTField;
            }
            set {
                this.hR_DA_DAINFO_LISTField = value;
                this.RaisePropertyChanged("HR_DA_DAINFO_LIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DAINFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dAIDField;
        
        private string dADMField;
        
        private int dALBField;
        
        private int dADMIDField;
        
        private int dANOField;
        
        private string dAJSRQField;
        
        private int bGQXField;
        
        private string bGQXNAMEField;
        
        private string aJNAMEField;
        
        private int dAXSField;
        
        private string dAXSNAMEField;
        
        private int dAMJField;
        
        private string dAMJNAMEField;
        
        private int tZCOUNTField;
        
        private int wJCOUNTField;
        
        private int aLLCOUNTField;
        
        private string lYNAMEField;
        
        private string tM1Field;
        
        private string tM2Field;
        
        private string rEMARKField;
        
        private int dAZTField;
        
        private int iSDELETEField;
        
        private int cJRField;
        
        private string cJRNAMEField;
        
        private string cJTIMEField;
        
        private int xGRField;
        
        private string xGRNAMEField;
        
        private string xGRTIMEField;
        
        private string dAJSRQKSField;
        
        private string dAJSRQJSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DAID {
            get {
                return this.dAIDField;
            }
            set {
                this.dAIDField = value;
                this.RaisePropertyChanged("DAID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DADM {
            get {
                return this.dADMField;
            }
            set {
                this.dADMField = value;
                this.RaisePropertyChanged("DADM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DALB {
            get {
                return this.dALBField;
            }
            set {
                this.dALBField = value;
                this.RaisePropertyChanged("DALB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DADMID {
            get {
                return this.dADMIDField;
            }
            set {
                this.dADMIDField = value;
                this.RaisePropertyChanged("DADMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int DANO {
            get {
                return this.dANOField;
            }
            set {
                this.dANOField = value;
                this.RaisePropertyChanged("DANO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DAJSRQ {
            get {
                return this.dAJSRQField;
            }
            set {
                this.dAJSRQField = value;
                this.RaisePropertyChanged("DAJSRQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int BGQX {
            get {
                return this.bGQXField;
            }
            set {
                this.bGQXField = value;
                this.RaisePropertyChanged("BGQX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BGQXNAME {
            get {
                return this.bGQXNAMEField;
            }
            set {
                this.bGQXNAMEField = value;
                this.RaisePropertyChanged("BGQXNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AJNAME {
            get {
                return this.aJNAMEField;
            }
            set {
                this.aJNAMEField = value;
                this.RaisePropertyChanged("AJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DAXS {
            get {
                return this.dAXSField;
            }
            set {
                this.dAXSField = value;
                this.RaisePropertyChanged("DAXS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string DAXSNAME {
            get {
                return this.dAXSNAMEField;
            }
            set {
                this.dAXSNAMEField = value;
                this.RaisePropertyChanged("DAXSNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int DAMJ {
            get {
                return this.dAMJField;
            }
            set {
                this.dAMJField = value;
                this.RaisePropertyChanged("DAMJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DAMJNAME {
            get {
                return this.dAMJNAMEField;
            }
            set {
                this.dAMJNAMEField = value;
                this.RaisePropertyChanged("DAMJNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int TZCOUNT {
            get {
                return this.tZCOUNTField;
            }
            set {
                this.tZCOUNTField = value;
                this.RaisePropertyChanged("TZCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int WJCOUNT {
            get {
                return this.wJCOUNTField;
            }
            set {
                this.wJCOUNTField = value;
                this.RaisePropertyChanged("WJCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ALLCOUNT {
            get {
                return this.aLLCOUNTField;
            }
            set {
                this.aLLCOUNTField = value;
                this.RaisePropertyChanged("ALLCOUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string LYNAME {
            get {
                return this.lYNAMEField;
            }
            set {
                this.lYNAMEField = value;
                this.RaisePropertyChanged("LYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string TM1 {
            get {
                return this.tM1Field;
            }
            set {
                this.tM1Field = value;
                this.RaisePropertyChanged("TM1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string TM2 {
            get {
                return this.tM2Field;
            }
            set {
                this.tM2Field = value;
                this.RaisePropertyChanged("TM2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int DAZT {
            get {
                return this.dAZTField;
            }
            set {
                this.dAZTField = value;
                this.RaisePropertyChanged("DAZT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int CJR {
            get {
                return this.cJRField;
            }
            set {
                this.cJRField = value;
                this.RaisePropertyChanged("CJR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string CJRNAME {
            get {
                return this.cJRNAMEField;
            }
            set {
                this.cJRNAMEField = value;
                this.RaisePropertyChanged("CJRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string CJTIME {
            get {
                return this.cJTIMEField;
            }
            set {
                this.cJTIMEField = value;
                this.RaisePropertyChanged("CJTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int XGR {
            get {
                return this.xGRField;
            }
            set {
                this.xGRField = value;
                this.RaisePropertyChanged("XGR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string XGRNAME {
            get {
                return this.xGRNAMEField;
            }
            set {
                this.xGRNAMEField = value;
                this.RaisePropertyChanged("XGRNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string XGRTIME {
            get {
                return this.xGRTIMEField;
            }
            set {
                this.xGRTIMEField = value;
                this.RaisePropertyChanged("XGRTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string DAJSRQKS {
            get {
                return this.dAJSRQKSField;
            }
            set {
                this.dAJSRQKSField = value;
                this.RaisePropertyChanged("DAJSRQKS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string DAJSRQJS {
            get {
                return this.dAJSRQJSField;
            }
            set {
                this.dAJSRQJSField = value;
                this.RaisePropertyChanged("DAJSRQJS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DADM_LIST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dADMIDField;
        
        private string dADMField;
        
        private int dALBField;
        
        private string dALBNAMEField;
        
        private string dADMNAMEField;
        
        private int iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DADMID {
            get {
                return this.dADMIDField;
            }
            set {
                this.dADMIDField = value;
                this.RaisePropertyChanged("DADMID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DADM {
            get {
                return this.dADMField;
            }
            set {
                this.dADMField = value;
                this.RaisePropertyChanged("DADM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DALB {
            get {
                return this.dALBField;
            }
            set {
                this.dALBField = value;
                this.RaisePropertyChanged("DALB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DALBNAME {
            get {
                return this.dALBNAMEField;
            }
            set {
                this.dALBNAMEField = value;
                this.RaisePropertyChanged("DALBNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DADMNAME {
            get {
                return this.dADMNAMEField;
            }
            set {
                this.dADMNAMEField = value;
                this.RaisePropertyChanged("DADMNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_DA_DADM_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HR_DA_DADM_LIST[] hR_DA_DADM_LISTField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public HR_DA_DADM_LIST[] HR_DA_DADM_LIST {
            get {
                return this.hR_DA_DADM_LISTField;
            }
            set {
                this.hR_DA_DADM_LISTField = value;
                this.RaisePropertyChanged("HR_DA_DADM_LIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DA_DAINFOSoapChannel : Sonluk.UI.Model.HR.DA_DAINFOService.DA_DAINFOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DA_DAINFOSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.HR.DA_DAINFOService.DA_DAINFOSoap>, Sonluk.UI.Model.HR.DA_DAINFOService.DA_DAINFOSoap {
        
        public DA_DAINFOSoapClient() {
        }
        
        public DA_DAINFOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DA_DAINFOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DA_DAINFOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DA_DAINFOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken) {
            return base.Channel.INSERT_DADM(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM_SELECT SELECT_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken) {
            return base.Channel.SELECT_DADM(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DADM(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DADM model, string ptoken) {
            return base.Channel.UPDATE_DADM(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN DELETE_DADM(int DADMID, string ptoken) {
            return base.Channel.DELETE_DADM(DADMID, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken) {
            return base.Channel.INSERT_DAINFO(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO_SELECT SELECT_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken) {
            return base.Channel.SELECT_DAINFO(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DAINFO(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAINFO model, string ptoken) {
            return base.Channel.UPDATE_DAINFO(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN DELETE_DAINFO(int DAID, string ptoken) {
            return base.Channel.DELETE_DAINFO(DAID, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN INSERT_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken) {
            return base.Channel.INSERT_DAJYJL(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL_SELECT SELECT_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken) {
            return base.Channel.SELECT_DAJYJL(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.DA_DAINFOService.MES_RETURN UPDATE_DAJYJL(Sonluk.UI.Model.HR.DA_DAINFOService.HR_DA_DAJYJL model, string ptoken) {
            return base.Channel.UPDATE_DAJYJL(model, ptoken);
        }
    }
}
