//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.MES.BAT_QLTYService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MES.BAT_QLTYService.BAT_QLTYSoap")]
    public interface BAT_QLTYSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT SELECT(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_SUM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT SELECT_SUM(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TMARK_SELECT_SUM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT TMARK_SELECT_SUM(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COVER", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN COVER(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB model, int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/COVER_TMARK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN COVER_TMARK(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB model, int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ACTION", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN ACTION(int RI, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN DELETE(int RI, int STAFFID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE_TMARK", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN DELETE_TMARK(int RI, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/STAFF_SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.MES.BAT_QLTYService.MES_SELECTOfMES_ZLRBB_STAFF STAFF_SELECT(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_STAFF model, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_ZLRBB_SEARCH : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int riField;
        
        private string dATESField;
        
        private string dATEEField;
        
        private string dATEMField;
        
        private string sDLINEField;
        
        private int sDLINEIDField;
        
        private int lbField;
        
        private int iSACTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int RI {
            get {
                return this.riField;
            }
            set {
                this.riField = value;
                this.RaisePropertyChanged("RI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DATES {
            get {
                return this.dATESField;
            }
            set {
                this.dATESField = value;
                this.RaisePropertyChanged("DATES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DATEE {
            get {
                return this.dATEEField;
            }
            set {
                this.dATEEField = value;
                this.RaisePropertyChanged("DATEE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DATEM {
            get {
                return this.dATEMField;
            }
            set {
                this.dATEMField = value;
                this.RaisePropertyChanged("DATEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SDLINE {
            get {
                return this.sDLINEField;
            }
            set {
                this.sDLINEField = value;
                this.RaisePropertyChanged("SDLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SDLINEID {
            get {
                return this.sDLINEIDField;
            }
            set {
                this.sDLINEIDField = value;
                this.RaisePropertyChanged("SDLINEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int LB {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
                this.RaisePropertyChanged("LB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int ISACTION {
            get {
                return this.iSACTIONField;
            }
            set {
                this.iSACTIONField = value;
                this.RaisePropertyChanged("ISACTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_SELECTOfMES_ZLRBB_STAFF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_ZLRBB_STAFF[] tListField;
        
        private string[] othersField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MES_ZLRBB_STAFF[] TList {
            get {
                return this.tListField;
            }
            set {
                this.tListField = value;
                this.RaisePropertyChanged("TList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Others {
            get {
                return this.othersField;
            }
            set {
                this.othersField = value;
                this.RaisePropertyChanged("Others");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_ZLRBB_STAFF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string sTAFFNOField;
        
        private string sTAFFNAMEField;
        
        private int iSACTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string STAFFNO {
            get {
                return this.sTAFFNOField;
            }
            set {
                this.sTAFFNOField = value;
                this.RaisePropertyChanged("STAFFNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ISACTION {
            get {
                return this.iSACTIONField;
            }
            set {
                this.iSACTIONField = value;
                this.RaisePropertyChanged("ISACTION");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_ZLRBB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bcField;
        
        private int bCIDField;
        
        private int zJHQRField;
        
        private int kxField;
        
        private int fKJTBField;
        
        private int gMZCRField;
        
        private int dJYZRField;
        
        private int xGZRField;
        
        private int fKCXField;
        
        private int dDMTBField;
        
        private float sDCLField;
        
        private int vYXField;
        
        private int vzField;
        
        private int vYSField;
        
        private int sDZYXCCDField;
        
        private int wGBLField;
        
        private int idField;
        
        private int hdField;
        
        private int tTBLField;
        
        private int lKCKField;
        
        private int tTPField;
        
        private int cpField;
        
        private int cXBLField;
        
        private int htField;
        
        private int wXGField;
        
        private int ycField;
        
        private int tDXCField;
        
        private int tPLSField;
        
        private int kXBLField;
        
        private int dGXField;
        
        private int tDTHField;
        
        private int rJZRBLField;
        
        private int wBDLField;
        
        private int yYBMField;
        
        private int qtField;
        
        private string jLTXRField;
        
        private int jLTXRIDField;
        
        private string jLTXRGHField;
        
        private string bzField;
        
        private int riField;
        
        private string dATEField;
        
        private string sDLINEField;
        
        private int sDLINEIDField;
        
        private int lbField;
        
        private int iSACTIONField;
        
        private int cJRIDField;
        
        private int iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BC {
            get {
                return this.bcField;
            }
            set {
                this.bcField = value;
                this.RaisePropertyChanged("BC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int BCID {
            get {
                return this.bCIDField;
            }
            set {
                this.bCIDField = value;
                this.RaisePropertyChanged("BCID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int ZJHQR {
            get {
                return this.zJHQRField;
            }
            set {
                this.zJHQRField = value;
                this.RaisePropertyChanged("ZJHQR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int KX {
            get {
                return this.kxField;
            }
            set {
                this.kxField = value;
                this.RaisePropertyChanged("KX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int FKJTB {
            get {
                return this.fKJTBField;
            }
            set {
                this.fKJTBField = value;
                this.RaisePropertyChanged("FKJTB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int GMZCR {
            get {
                return this.gMZCRField;
            }
            set {
                this.gMZCRField = value;
                this.RaisePropertyChanged("GMZCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DJYZR {
            get {
                return this.dJYZRField;
            }
            set {
                this.dJYZRField = value;
                this.RaisePropertyChanged("DJYZR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int XGZR {
            get {
                return this.xGZRField;
            }
            set {
                this.xGZRField = value;
                this.RaisePropertyChanged("XGZR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int FKCX {
            get {
                return this.fKCXField;
            }
            set {
                this.fKCXField = value;
                this.RaisePropertyChanged("FKCX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int DDMTB {
            get {
                return this.dDMTBField;
            }
            set {
                this.dDMTBField = value;
                this.RaisePropertyChanged("DDMTB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public float SDCL {
            get {
                return this.sDCLField;
            }
            set {
                this.sDCLField = value;
                this.RaisePropertyChanged("SDCL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int VYX {
            get {
                return this.vYXField;
            }
            set {
                this.vYXField = value;
                this.RaisePropertyChanged("VYX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int VZ {
            get {
                return this.vzField;
            }
            set {
                this.vzField = value;
                this.RaisePropertyChanged("VZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int VYS {
            get {
                return this.vYSField;
            }
            set {
                this.vYSField = value;
                this.RaisePropertyChanged("VYS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int SDZYXCCD {
            get {
                return this.sDZYXCCDField;
            }
            set {
                this.sDZYXCCDField = value;
                this.RaisePropertyChanged("SDZYXCCD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int WGBL {
            get {
                return this.wGBLField;
            }
            set {
                this.wGBLField = value;
                this.RaisePropertyChanged("WGBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int HD {
            get {
                return this.hdField;
            }
            set {
                this.hdField = value;
                this.RaisePropertyChanged("HD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int TTBL {
            get {
                return this.tTBLField;
            }
            set {
                this.tTBLField = value;
                this.RaisePropertyChanged("TTBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int LKCK {
            get {
                return this.lKCKField;
            }
            set {
                this.lKCKField = value;
                this.RaisePropertyChanged("LKCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int TTP {
            get {
                return this.tTPField;
            }
            set {
                this.tTPField = value;
                this.RaisePropertyChanged("TTP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int CP {
            get {
                return this.cpField;
            }
            set {
                this.cpField = value;
                this.RaisePropertyChanged("CP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int CXBL {
            get {
                return this.cXBLField;
            }
            set {
                this.cXBLField = value;
                this.RaisePropertyChanged("CXBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public int HT {
            get {
                return this.htField;
            }
            set {
                this.htField = value;
                this.RaisePropertyChanged("HT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int WXG {
            get {
                return this.wXGField;
            }
            set {
                this.wXGField = value;
                this.RaisePropertyChanged("WXG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int YC {
            get {
                return this.ycField;
            }
            set {
                this.ycField = value;
                this.RaisePropertyChanged("YC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int TDXC {
            get {
                return this.tDXCField;
            }
            set {
                this.tDXCField = value;
                this.RaisePropertyChanged("TDXC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int TPLS {
            get {
                return this.tPLSField;
            }
            set {
                this.tPLSField = value;
                this.RaisePropertyChanged("TPLS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int KXBL {
            get {
                return this.kXBLField;
            }
            set {
                this.kXBLField = value;
                this.RaisePropertyChanged("KXBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int DGX {
            get {
                return this.dGXField;
            }
            set {
                this.dGXField = value;
                this.RaisePropertyChanged("DGX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public int TDTH {
            get {
                return this.tDTHField;
            }
            set {
                this.tDTHField = value;
                this.RaisePropertyChanged("TDTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public int RJZRBL {
            get {
                return this.rJZRBLField;
            }
            set {
                this.rJZRBLField = value;
                this.RaisePropertyChanged("RJZRBL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public int WBDL {
            get {
                return this.wBDLField;
            }
            set {
                this.wBDLField = value;
                this.RaisePropertyChanged("WBDL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public int YYBM {
            get {
                return this.yYBMField;
            }
            set {
                this.yYBMField = value;
                this.RaisePropertyChanged("YYBM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public int QT {
            get {
                return this.qtField;
            }
            set {
                this.qtField = value;
                this.RaisePropertyChanged("QT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string JLTXR {
            get {
                return this.jLTXRField;
            }
            set {
                this.jLTXRField = value;
                this.RaisePropertyChanged("JLTXR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int JLTXRID {
            get {
                return this.jLTXRIDField;
            }
            set {
                this.jLTXRIDField = value;
                this.RaisePropertyChanged("JLTXRID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string JLTXRGH {
            get {
                return this.jLTXRGHField;
            }
            set {
                this.jLTXRGHField = value;
                this.RaisePropertyChanged("JLTXRGH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string BZ {
            get {
                return this.bzField;
            }
            set {
                this.bzField = value;
                this.RaisePropertyChanged("BZ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public int RI {
            get {
                return this.riField;
            }
            set {
                this.riField = value;
                this.RaisePropertyChanged("RI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string DATE {
            get {
                return this.dATEField;
            }
            set {
                this.dATEField = value;
                this.RaisePropertyChanged("DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string SDLINE {
            get {
                return this.sDLINEField;
            }
            set {
                this.sDLINEField = value;
                this.RaisePropertyChanged("SDLINE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public int SDLINEID {
            get {
                return this.sDLINEIDField;
            }
            set {
                this.sDLINEIDField = value;
                this.RaisePropertyChanged("SDLINEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public int LB {
            get {
                return this.lbField;
            }
            set {
                this.lbField = value;
                this.RaisePropertyChanged("LB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public int ISACTION {
            get {
                return this.iSACTIONField;
            }
            set {
                this.iSACTIONField = value;
                this.RaisePropertyChanged("ISACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public int CJRID {
            get {
                return this.cJRIDField;
            }
            set {
                this.cJRIDField = value;
                this.RaisePropertyChanged("CJRID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public int ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_ZLRBB_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_ZLRBB[] mES_ZLRBBField;
        
        private MES_RETURN mES_RETURNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public MES_ZLRBB[] MES_ZLRBB {
            get {
                return this.mES_ZLRBBField;
            }
            set {
                this.mES_ZLRBBField = value;
                this.RaisePropertyChanged("MES_ZLRBB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BAT_QLTYSoapChannel : Sonluk.UI.Model.MES.BAT_QLTYService.BAT_QLTYSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BAT_QLTYSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.MES.BAT_QLTYService.BAT_QLTYSoap>, Sonluk.UI.Model.MES.BAT_QLTYService.BAT_QLTYSoap {
        
        public BAT_QLTYSoapClient() {
        }
        
        public BAT_QLTYSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BAT_QLTYSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BAT_QLTYSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BAT_QLTYSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT SELECT(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken) {
            return base.Channel.SELECT(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT SELECT_SUM(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken) {
            return base.Channel.SELECT_SUM(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SELECT TMARK_SELECT_SUM(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_SEARCH model, string ptoken) {
            return base.Channel.TMARK_SELECT_SUM(model, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN COVER(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB model, int STAFFID, string ptoken) {
            return base.Channel.COVER(model, STAFFID, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN COVER_TMARK(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB model, int STAFFID, string ptoken) {
            return base.Channel.COVER_TMARK(model, STAFFID, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN ACTION(int RI, string ptoken) {
            return base.Channel.ACTION(RI, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN DELETE(int RI, int STAFFID, string ptoken) {
            return base.Channel.DELETE(RI, STAFFID, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_RETURN DELETE_TMARK(int RI, string ptoken) {
            return base.Channel.DELETE_TMARK(RI, ptoken);
        }
        
        public Sonluk.UI.Model.MES.BAT_QLTYService.MES_SELECTOfMES_ZLRBB_STAFF STAFF_SELECT(Sonluk.UI.Model.MES.BAT_QLTYService.MES_ZLRBB_STAFF model, string ptoken) {
            return base.Channel.STAFF_SELECT(model, ptoken);
        }
    }
}
