//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.HR.SY_MYINFOService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HR.SY_MYINFOService.WS_HR_SY_MYINFOSoap")]
    public interface WS_HR_SY_MYINFOSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JM_ISTRUE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN JM_ISTRUE(string MYPW, int STAFFID, int LB, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INSERT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN INSERT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT_REPORT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO_SELECT SELECT_REPORT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN UPDATE(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, int LB, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SELECT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO_SELECT SELECT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, int LB, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_SY_MYINFO_SELECT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MES_RETURN mES_RETURNField;
        
        private System.Data.DataTable dATALISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataTable DATALIST {
            get {
                return this.dATALISTField;
            }
            set {
                this.dATALISTField = value;
                this.RaisePropertyChanged("DATALIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HR_SY_MYINFO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mYNAMEField;
        
        private int mYLBField;
        
        private string mYMMField;
        
        private string mYMMPField;
        
        private int sTAFFIDField;
        
        private int mYIDField;
        
        private string mYPWOLDField;
        
        private string mYPWNEWField;
        
        private string sYPWField;
        
        private string gYPWField;
        
        private string mYPWField;
        
        private string sTAFFUSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MYNAME {
            get {
                return this.mYNAMEField;
            }
            set {
                this.mYNAMEField = value;
                this.RaisePropertyChanged("MYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MYLB {
            get {
                return this.mYLBField;
            }
            set {
                this.mYLBField = value;
                this.RaisePropertyChanged("MYLB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MYMM {
            get {
                return this.mYMMField;
            }
            set {
                this.mYMMField = value;
                this.RaisePropertyChanged("MYMM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MYMMP {
            get {
                return this.mYMMPField;
            }
            set {
                this.mYMMPField = value;
                this.RaisePropertyChanged("MYMMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int MYID {
            get {
                return this.mYIDField;
            }
            set {
                this.mYIDField = value;
                this.RaisePropertyChanged("MYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MYPWOLD {
            get {
                return this.mYPWOLDField;
            }
            set {
                this.mYPWOLDField = value;
                this.RaisePropertyChanged("MYPWOLD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MYPWNEW {
            get {
                return this.mYPWNEWField;
            }
            set {
                this.mYPWNEWField = value;
                this.RaisePropertyChanged("MYPWNEW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SYPW {
            get {
                return this.sYPWField;
            }
            set {
                this.sYPWField = value;
                this.RaisePropertyChanged("SYPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string GYPW {
            get {
                return this.gYPWField;
            }
            set {
                this.gYPWField = value;
                this.RaisePropertyChanged("GYPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MYPW {
            get {
                return this.mYPWField;
            }
            set {
                this.mYPWField = value;
                this.RaisePropertyChanged("MYPW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string STAFFUSER {
            get {
                return this.sTAFFUSERField;
            }
            set {
                this.sTAFFUSERField = value;
                this.RaisePropertyChanged("STAFFUSER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_HR_SY_MYINFOSoapChannel : Sonluk.UI.Model.HR.SY_MYINFOService.WS_HR_SY_MYINFOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_HR_SY_MYINFOSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.HR.SY_MYINFOService.WS_HR_SY_MYINFOSoap>, Sonluk.UI.Model.HR.SY_MYINFOService.WS_HR_SY_MYINFOSoap {
        
        public WS_HR_SY_MYINFOSoapClient() {
        }
        
        public WS_HR_SY_MYINFOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_HR_SY_MYINFOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HR_SY_MYINFOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_HR_SY_MYINFOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN JM_ISTRUE(string MYPW, int STAFFID, int LB, string ptoken) {
            return base.Channel.JM_ISTRUE(MYPW, STAFFID, LB, ptoken);
        }
        
        public Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN INSERT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, string ptoken) {
            return base.Channel.INSERT(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO_SELECT SELECT_REPORT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, string ptoken) {
            return base.Channel.SELECT_REPORT(model, ptoken);
        }
        
        public Sonluk.UI.Model.HR.SY_MYINFOService.MES_RETURN UPDATE(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, int LB, string ptoken) {
            return base.Channel.UPDATE(model, LB, ptoken);
        }
        
        public Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO_SELECT SELECT(Sonluk.UI.Model.HR.SY_MYINFOService.HR_SY_MYINFO model, int LB, string ptoken) {
            return base.Channel.SELECT(model, LB, ptoken);
        }
    }
}
