//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonluk.UI.Model.S5.SY_CHECKPOINTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="S5.SY_CHECKPOINTService.SY_CHECKPOINTSoap")]
    public interface SY_CHECKPOINTSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT[] Read(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Compare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT[] Compare(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadaddDepName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINTList[] ReadaddDepName(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Create(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Create_All(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Update_All(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Delete_All(int pointid, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_ByPointID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE Select_ByPointID(int PointID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UPDATE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN UPDATE(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DELETE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN DELETE(int ID, string ptoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Select_CHECKPOINT_byParms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE Select_CHECKPOINT_byParms(int pointId, int staffid, string ptoken);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_CHECKPOINT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pOINTIDField;
        
        private string lOCATIONMSField;
        
        private string pOINTMSField;
        
        private int dIDField;
        
        private int aCTIONField;
        
        private bool iSDELETEField;
        
        private int djField;
        
        private string sHOWNAMEMSField;
        
        private string kSTIMEField;
        
        private string jSTIMEField;
        
        private int nUMField;
        
        private int iNFOIDField;
        
        private string dEPARTMSField;
        
        private int fREQUENCYField;
        
        private string fREQUENCYNAMEField;
        
        private int iSNEEDField;
        
        private string cODEField;
        
        private string vIEWSField;
        
        private int iSREPORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int POINTID {
            get {
                return this.pOINTIDField;
            }
            set {
                this.pOINTIDField = value;
                this.RaisePropertyChanged("POINTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LOCATIONMS {
            get {
                return this.lOCATIONMSField;
            }
            set {
                this.lOCATIONMSField = value;
                this.RaisePropertyChanged("LOCATIONMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string POINTMS {
            get {
                return this.pOINTMSField;
            }
            set {
                this.pOINTMSField = value;
                this.RaisePropertyChanged("POINTMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("DID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DJ {
            get {
                return this.djField;
            }
            set {
                this.djField = value;
                this.RaisePropertyChanged("DJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SHOWNAMEMS {
            get {
                return this.sHOWNAMEMSField;
            }
            set {
                this.sHOWNAMEMSField = value;
                this.RaisePropertyChanged("SHOWNAMEMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KSTIME {
            get {
                return this.kSTIMEField;
            }
            set {
                this.kSTIMEField = value;
                this.RaisePropertyChanged("KSTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string JSTIME {
            get {
                return this.jSTIMEField;
            }
            set {
                this.jSTIMEField = value;
                this.RaisePropertyChanged("JSTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
                this.RaisePropertyChanged("NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int INFOID {
            get {
                return this.iNFOIDField;
            }
            set {
                this.iNFOIDField = value;
                this.RaisePropertyChanged("INFOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DEPARTMS {
            get {
                return this.dEPARTMSField;
            }
            set {
                this.dEPARTMSField = value;
                this.RaisePropertyChanged("DEPARTMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FREQUENCYNAME {
            get {
                return this.fREQUENCYNAMEField;
            }
            set {
                this.fREQUENCYNAMEField = value;
                this.RaisePropertyChanged("FREQUENCYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public int ISNEED {
            get {
                return this.iSNEEDField;
            }
            set {
                this.iSNEEDField = value;
                this.RaisePropertyChanged("ISNEED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string VIEWS {
            get {
                return this.vIEWSField;
            }
            set {
                this.vIEWSField = value;
                this.RaisePropertyChanged("VIEWS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int ISREPORT {
            get {
                return this.iSREPORTField;
            }
            set {
                this.iSREPORTField = value;
                this.RaisePropertyChanged("ISREPORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_RELATIONSHIPBINDList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int oBJ1Field;
        
        private int oBJ2Field;
        
        private int tYPEField;
        
        private int aCTIONField;
        
        private string oBJ1NAMEField;
        
        private string oBJ2NAMEField;
        
        private string tYPENAMEField;
        
        private string tYPEREMARKField;
        
        private string dpField;
        
        private string rEMARKField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OBJ1 {
            get {
                return this.oBJ1Field;
            }
            set {
                this.oBJ1Field = value;
                this.RaisePropertyChanged("OBJ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OBJ2 {
            get {
                return this.oBJ2Field;
            }
            set {
                this.oBJ2Field = value;
                this.RaisePropertyChanged("OBJ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OBJ1NAME {
            get {
                return this.oBJ1NAMEField;
            }
            set {
                this.oBJ1NAMEField = value;
                this.RaisePropertyChanged("OBJ1NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OBJ2NAME {
            get {
                return this.oBJ2NAMEField;
            }
            set {
                this.oBJ2NAMEField = value;
                this.RaisePropertyChanged("OBJ2NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TYPENAME {
            get {
                return this.tYPENAMEField;
            }
            set {
                this.tYPENAMEField = value;
                this.RaisePropertyChanged("TYPENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TYPEREMARK {
            get {
                return this.tYPEREMARKField;
            }
            set {
                this.tYPEREMARKField = value;
                this.RaisePropertyChanged("TYPEREMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Dp {
            get {
                return this.dpField;
            }
            set {
                this.dpField = value;
                this.RaisePropertyChanged("Dp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_STAFF_DEP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int sTAFFIDField;
        
        private int dEPTIDField;
        
        private int tYPEIDField;
        
        private string sTAFFNAMEField;
        
        private string dEPTNAMEField;
        
        private string tYPENAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int STAFFID {
            get {
                return this.sTAFFIDField;
            }
            set {
                this.sTAFFIDField = value;
                this.RaisePropertyChanged("STAFFID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DEPTID {
            get {
                return this.dEPTIDField;
            }
            set {
                this.dEPTIDField = value;
                this.RaisePropertyChanged("DEPTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TYPEID {
            get {
                return this.tYPEIDField;
            }
            set {
                this.tYPEIDField = value;
                this.RaisePropertyChanged("TYPEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string STAFFNAME {
            get {
                return this.sTAFFNAMEField;
            }
            set {
                this.sTAFFNAMEField = value;
                this.RaisePropertyChanged("STAFFNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DEPTNAME {
            get {
                return this.dEPTNAMEField;
            }
            set {
                this.dEPTNAMEField = value;
                this.RaisePropertyChanged("DEPTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TYPENAME {
            get {
                return this.tYPENAMEField;
            }
            set {
                this.tYPENAMEField = value;
                this.RaisePropertyChanged("TYPENAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_CHECK_INFODETAILList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dETAILIDField;
        
        private int iNFOIDField;
        
        private int tYPEIDField;
        
        private string tYPEMSField;
        
        private int sCROEIDField;
        
        private string sCROEMSField;
        
        private string jLTIMEField;
        
        private string rEMARKField;
        
        private int aCTIONField;
        
        private bool iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DETAILID {
            get {
                return this.dETAILIDField;
            }
            set {
                this.dETAILIDField = value;
                this.RaisePropertyChanged("DETAILID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int INFOID {
            get {
                return this.iNFOIDField;
            }
            set {
                this.iNFOIDField = value;
                this.RaisePropertyChanged("INFOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TYPEID {
            get {
                return this.tYPEIDField;
            }
            set {
                this.tYPEIDField = value;
                this.RaisePropertyChanged("TYPEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TYPEMS {
            get {
                return this.tYPEMSField;
            }
            set {
                this.tYPEMSField = value;
                this.RaisePropertyChanged("TYPEMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SCROEID {
            get {
                return this.sCROEIDField;
            }
            set {
                this.sCROEIDField = value;
                this.RaisePropertyChanged("SCROEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SCROEMS {
            get {
                return this.sCROEMSField;
            }
            set {
                this.sCROEMSField = value;
                this.RaisePropertyChanged("SCROEMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string JLTIME {
            get {
                return this.jLTIMEField;
            }
            set {
                this.jLTIMEField = value;
                this.RaisePropertyChanged("JLTIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string REMARK {
            get {
                return this.rEMARKField;
            }
            set {
                this.rEMARKField = value;
                this.RaisePropertyChanged("REMARK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_CHECKDETAILS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dETAILIDField;
        
        private int cATEGROYIDField;
        
        private string dETAILMSField;
        
        private int aCTIONField;
        
        private bool iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DETAILID {
            get {
                return this.dETAILIDField;
            }
            set {
                this.dETAILIDField = value;
                this.RaisePropertyChanged("DETAILID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CATEGROYID {
            get {
                return this.cATEGROYIDField;
            }
            set {
                this.cATEGROYIDField = value;
                this.RaisePropertyChanged("CATEGROYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DETAILMS {
            get {
                return this.dETAILMSField;
            }
            set {
                this.dETAILMSField = value;
                this.RaisePropertyChanged("DETAILMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_DICT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dICIDField;
        
        private int tYPEIDField;
        
        private string dICNAMEField;
        
        private string dICMEMOField;
        
        private int aCTIONField;
        
        private bool iSDELETEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DICID {
            get {
                return this.dICIDField;
            }
            set {
                this.dICIDField = value;
                this.RaisePropertyChanged("DICID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TYPEID {
            get {
                return this.tYPEIDField;
            }
            set {
                this.tYPEIDField = value;
                this.RaisePropertyChanged("TYPEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DICNAME {
            get {
                return this.dICNAMEField;
            }
            set {
                this.dICNAMEField = value;
                this.RaisePropertyChanged("DICNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DICMEMO {
            get {
                return this.dICMEMOField;
            }
            set {
                this.dICMEMOField = value;
                this.RaisePropertyChanged("DICMEMO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_CHECKPOINT_CREATE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FIVES_SY_CHECKPOINT fIVES_SY_CHECKPOINTField;
        
        private FIVES_SY_DICT[] gwField;
        
        private FIVES_SY_CHECKDETAILS[] cHECKDETAIField;
        
        private FIVES_CHECK_INFODETAILList[] lASTCHECKINFODETAILField;
        
        private MES_RETURN mES_RETURNField;
        
        private FIVES_STAFF_DEP fIVES_STAFF_DEPField;
        
        private FIVES_SY_RELATIONSHIPBINDList[] gWLISTField;
        
        private FIVES_SY_RELATIONSHIPBINDList[] mXLISTField;
        
        private FIVES_SY_DICT[] pFLISTField;
        
        private FIVES_SY_RELATIONSHIPBINDList[] fLlistField;
        
        private string jydStrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FIVES_SY_CHECKPOINT FIVES_SY_CHECKPOINT {
            get {
                return this.fIVES_SY_CHECKPOINTField;
            }
            set {
                this.fIVES_SY_CHECKPOINTField = value;
                this.RaisePropertyChanged("FIVES_SY_CHECKPOINT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public FIVES_SY_DICT[] GW {
            get {
                return this.gwField;
            }
            set {
                this.gwField = value;
                this.RaisePropertyChanged("GW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public FIVES_SY_CHECKDETAILS[] CHECKDETAI {
            get {
                return this.cHECKDETAIField;
            }
            set {
                this.cHECKDETAIField = value;
                this.RaisePropertyChanged("CHECKDETAI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public FIVES_CHECK_INFODETAILList[] LASTCHECKINFODETAIL {
            get {
                return this.lASTCHECKINFODETAILField;
            }
            set {
                this.lASTCHECKINFODETAILField = value;
                this.RaisePropertyChanged("LASTCHECKINFODETAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MES_RETURN MES_RETURN {
            get {
                return this.mES_RETURNField;
            }
            set {
                this.mES_RETURNField = value;
                this.RaisePropertyChanged("MES_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public FIVES_STAFF_DEP FIVES_STAFF_DEP {
            get {
                return this.fIVES_STAFF_DEPField;
            }
            set {
                this.fIVES_STAFF_DEPField = value;
                this.RaisePropertyChanged("FIVES_STAFF_DEP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public FIVES_SY_RELATIONSHIPBINDList[] GWLIST {
            get {
                return this.gWLISTField;
            }
            set {
                this.gWLISTField = value;
                this.RaisePropertyChanged("GWLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public FIVES_SY_RELATIONSHIPBINDList[] MXLIST {
            get {
                return this.mXLISTField;
            }
            set {
                this.mXLISTField = value;
                this.RaisePropertyChanged("MXLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public FIVES_SY_DICT[] PFLIST {
            get {
                return this.pFLISTField;
            }
            set {
                this.pFLISTField = value;
                this.RaisePropertyChanged("PFLIST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public FIVES_SY_RELATIONSHIPBINDList[] FLlist {
            get {
                return this.fLlistField;
            }
            set {
                this.fLlistField = value;
                this.RaisePropertyChanged("FLlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string JydStr {
            get {
                return this.jydStrField;
            }
            set {
                this.jydStrField = value;
                this.RaisePropertyChanged("JydStr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MES_RETURN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private int tIDField;
        
        private string gcField;
        
        private string tmField;
        
        private string bhField;
        
        private int xhField;
        
        private int tMSXField;
        
        private string mSGNOField;
        
        private int iSCLMSGField;
        
        private string cODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int TID {
            get {
                return this.tIDField;
            }
            set {
                this.tIDField = value;
                this.RaisePropertyChanged("TID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string GC {
            get {
                return this.gcField;
            }
            set {
                this.gcField = value;
                this.RaisePropertyChanged("GC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TM {
            get {
                return this.tmField;
            }
            set {
                this.tmField = value;
                this.RaisePropertyChanged("TM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BH {
            get {
                return this.bhField;
            }
            set {
                this.bhField = value;
                this.RaisePropertyChanged("BH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int XH {
            get {
                return this.xhField;
            }
            set {
                this.xhField = value;
                this.RaisePropertyChanged("XH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int TMSX {
            get {
                return this.tMSXField;
            }
            set {
                this.tMSXField = value;
                this.RaisePropertyChanged("TMSX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MSGNO {
            get {
                return this.mSGNOField;
            }
            set {
                this.mSGNOField = value;
                this.RaisePropertyChanged("MSGNO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ISCLMSG {
            get {
                return this.iSCLMSGField;
            }
            set {
                this.iSCLMSGField = value;
                this.RaisePropertyChanged("ISCLMSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FIVES_SY_CHECKPOINTList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int pOINTIDField;
        
        private string lOCATIONMSField;
        
        private string pOINTMSField;
        
        private int dIDField;
        
        private int aCTIONField;
        
        private bool iSDELETEField;
        
        private string dNAMEField;
        
        private int djField;
        
        private int fREQUENCYField;
        
        private string fREQUENCYNAMEField;
        
        private int iSNEEDField;
        
        private string cODEField;
        
        private string vIEWSField;
        
        private int iSREPORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int POINTID {
            get {
                return this.pOINTIDField;
            }
            set {
                this.pOINTIDField = value;
                this.RaisePropertyChanged("POINTID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LOCATIONMS {
            get {
                return this.lOCATIONMSField;
            }
            set {
                this.lOCATIONMSField = value;
                this.RaisePropertyChanged("LOCATIONMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string POINTMS {
            get {
                return this.pOINTMSField;
            }
            set {
                this.pOINTMSField = value;
                this.RaisePropertyChanged("POINTMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DID {
            get {
                return this.dIDField;
            }
            set {
                this.dIDField = value;
                this.RaisePropertyChanged("DID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ACTION {
            get {
                return this.aCTIONField;
            }
            set {
                this.aCTIONField = value;
                this.RaisePropertyChanged("ACTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ISDELETE {
            get {
                return this.iSDELETEField;
            }
            set {
                this.iSDELETEField = value;
                this.RaisePropertyChanged("ISDELETE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DNAME {
            get {
                return this.dNAMEField;
            }
            set {
                this.dNAMEField = value;
                this.RaisePropertyChanged("DNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int DJ {
            get {
                return this.djField;
            }
            set {
                this.djField = value;
                this.RaisePropertyChanged("DJ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int FREQUENCY {
            get {
                return this.fREQUENCYField;
            }
            set {
                this.fREQUENCYField = value;
                this.RaisePropertyChanged("FREQUENCY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FREQUENCYNAME {
            get {
                return this.fREQUENCYNAMEField;
            }
            set {
                this.fREQUENCYNAMEField = value;
                this.RaisePropertyChanged("FREQUENCYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int ISNEED {
            get {
                return this.iSNEEDField;
            }
            set {
                this.iSNEEDField = value;
                this.RaisePropertyChanged("ISNEED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string VIEWS {
            get {
                return this.vIEWSField;
            }
            set {
                this.vIEWSField = value;
                this.RaisePropertyChanged("VIEWS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int ISREPORT {
            get {
                return this.iSREPORTField;
            }
            set {
                this.iSREPORTField = value;
                this.RaisePropertyChanged("ISREPORT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SY_CHECKPOINTSoapChannel : Sonluk.UI.Model.S5.SY_CHECKPOINTService.SY_CHECKPOINTSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SY_CHECKPOINTSoapClient : System.ServiceModel.ClientBase<Sonluk.UI.Model.S5.SY_CHECKPOINTService.SY_CHECKPOINTSoap>, Sonluk.UI.Model.S5.SY_CHECKPOINTService.SY_CHECKPOINTSoap {
        
        public SY_CHECKPOINTSoapClient() {
        }
        
        public SY_CHECKPOINTSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SY_CHECKPOINTSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_CHECKPOINTSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SY_CHECKPOINTSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT[] Read(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken) {
            return base.Channel.Read(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT[] Compare(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken) {
            return base.Channel.Compare(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINTList[] ReadaddDepName(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken) {
            return base.Channel.ReadaddDepName(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Create(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken) {
            return base.Channel.Create(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Create_All(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE model, string ptoken) {
            return base.Channel.Create_All(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Update_All(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE model, string ptoken) {
            return base.Channel.Update_All(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN Delete_All(int pointid, string ptoken) {
            return base.Channel.Delete_All(pointid, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE Select_ByPointID(int PointID, string ptoken) {
            return base.Channel.Select_ByPointID(PointID, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN UPDATE(Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT model, string ptoken) {
            return base.Channel.UPDATE(model, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.MES_RETURN DELETE(int ID, string ptoken) {
            return base.Channel.DELETE(ID, ptoken);
        }
        
        public Sonluk.UI.Model.S5.SY_CHECKPOINTService.FIVES_SY_CHECKPOINT_CREATE Select_CHECKPOINT_byParms(int pointId, int staffid, string ptoken) {
            return base.Channel.Select_CHECKPOINT_byParms(pointId, staffid, ptoken);
        }
    }
}
